### ISSUE TITLE
Sign in with google

### ISSUE THREAD

**Issue by nadzic** [wix/Detox#1016]
We have in our react native app signing in with google. So when you click on login button it opens the system message and asks: "App" Wants to use "google.com" to Sign In. (Cancel/Continue) possible to select and then it opens browser window.

There are few questions about it:

- We cannot with detox tap to Continue, why?

- Anyway if we succeed to tap on Continue, is then possible to fill out the fields in the browser? (Email, Password for log in)?

- Or do we need to mock signing google user to log in successfully and then go to next steps? I have read something like that here: https://github.com/wix/detox/issues/287

Thank you very much for your answers

**Comment by LeoNatan** [comment]
It’s not possible to tap on the Continue button because it’s presented from a different process. Likewise, the Safari view controller comes from a different process too. 

You will need to mock the outer API to give you a predetermined token. 

https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md
