### ISSUE TITLE
Driver for custom NativeModule keyboard

### ISSUE THREAD

**Issue by wontonst** [wix/Detox#1031]
I saw #119 but I'm using a NativeModule as opposed to `react-native-keyboard-input`

#### Description

The issue I'm facing is that there is a custom keyboard that is used by the Braintree library. Just as how the iOS keyboard doesn't show up in the components hierarchy, the custom keyboard used by Braintree doesn't either, so Detox is effectively blind to it. I can't simply `typeText` since the keyboard doesn't have the standard format. `typeText` simply does nothing and fails silenty. Here's what it looks like.

![image](https://user-images.githubusercontent.com/2030556/48229989-70945380-e35e-11e8-8457-fa8682de2eb6.png)

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.0.5
* React Native: 0.57.3
* Node: 10.8.0
* Device: iPhone X
* Xcode: 10.1
* macOS: Mojave

**Comment by LeoNatan** [comment]
There isn't anything special about these buttons. Give them a test identifier (or in iOS, `accessibilityIdentifier`) and then `.tap()` your buttons `byId()`.

This is more suited for Stack Overflow. Please open your questions there.

**Comment by wontonst** [comment]
Please hear me out before assuming user error. 
Ignoring how it’s a third party library, the issue is the keyboard doesn’t show up in the hierarchy. It’s not that it doesn’t have an id, it’s that it’s simply not there. I tested this by going to the view you see in the screenshot and failing the test to see what detox sees. 

I’ve even tried tapAtPoint but it dismissed the keyboard because the tap ends up *behind the keyboard*, dismissing it.

**Comment by wontonst** [comment]
To further clarify, what I’m saying is let’s say you open up a regular keyboard. Instead of typeText(“hi”), I want to tap the individual characters like hElement.tap() iElement.tap()

**Comment by LeoNatan** [comment]
I am not assuming user error, only pointing you to Stack Overflow for higher exposure.

What you say makes sense, since the keyboard (and custom input views) appear on a different window (that's different than a view) from the usual app window. If I recall correctly, Earl Grey should find elements by identifier, even if those elements are on a different window. If this is not the case, there is little we can do bar extending Earl Grey, which is out of scope.

You say that it's a third party component. If you have access to the code, add an `accessibilityIdentifier` to one of the custom input buttons, and see that `await expect(element(by.id("<yourIdentifier>"))).toBeVisible();` succeeds when the keyboard is shown. 
If it does, you should open an issue with the third party vendor, asking for identifiers for all buttons.
If it doesn't, I direct you to open an issue [here](https://github.com/google/EarlGrey/issues), asking for this feature. If implemented, we will then be able to support it.

**Comment by wontonst** [comment]
@LeoNatan Thank you for your response, I've posted a stackoverflow at https://stackoverflow.com/questions/53231950/how-to-interact-with-custom-keyboard-in-detox and hopefully can come up with a solution.

**Comment by LeoNatan** [comment]
Have you tried what I suggested?

**Comment by wontonst** [comment]
I took a look at the detox printout again and I'm certain it's not there. I took a glance at the Earl Grey repo and I believe it the amount of work necessary would exceed my allotted time so I'll have to find a workaround.
