### ISSUE TITLE
Using in a physical android device 

### ISSUE THREAD

**Issue by jramalho** [wix/Detox#1200]
**Describe the bug**
When i try to use it on a physical device, it boot the app but never automate a test.
This using the examples files.

**To Reproduce**

1. Download base project
2. detox build the base react-native project or react-native-jest projet
3. detox test

the issue happen on both react-native or react-native-jest demo project on the examples folder

**Expected behavior**
It should automate tests

**Screenshots**

**Environment (please complete the following information):**
 - Detox: 10.0.12
 - React Native: 0.51.1
 - Device: Moto e 2
 - OS: Linux Ubuntu

**Device and Verbose Detox Logs**
1) "before all" hook

  0 passing (2m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  0 passing (2m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by JsonDo** [comment]
Hello @jramalho ,
For me to be able to test on physical Android devices, I have to change some adb settings first.

With only one device connected through USB, I usually do the following:

1. `adb -d reverse tcp:8099 tcp:8099`
1. `detox run-server`
1. `detox test -c yourConfigHere`

In your configuration file, instead of giving detox the emulator name, give it its adb serial number, obtained by running `adb -d devices`.
