### ISSUE TITLE
(Android) Native error reporting

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1213]
**Is your feature request related to a problem? Please describe.**
When native side crashes while a test is running, the testing node remains unaware. Therefore, the test only fails after a (long) timeout is expired, and the native stacktrace isn't available.

**Describe the solution you'd like**
Native stacktrace should show immediately as the app crashes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LeoNatan** [comment]
This is what we do on iOS for ObjC & C++ crashes:

https://github.com/wix/Detox/blob/master/detox/ios/Detox/DetoxCrashHandler.mm

You can probably use this for Android as well. We override the system's std::set_terminate so that all unhandled exceptions come to our handler. We also add signal handlers for other crashes.
