### ISSUE TITLE
device.relaunchApp was supposedly removed as of Detox 6, but still is defined

### ISSUE THREAD

**Issue by solkaz** [wix/Detox#1217]
Per  [the docs for `device`](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicerelaunchappparams), `relaunchApp` was deprecated and supposed to have been removed as of Detox 6, but [it is still defined](https://github.com/wix/Detox/blob/master/detox/src/devices/Device.js#L118)

**Comment by solkaz** [comment]
There are still some docs that reference [`relaunchApp`](https://github.com/wix/Detox/search?l=Markdown&q=relaunchApp) as well

**Comment by LeoNatan** [comment]
Hello,

It has not been removed because we do not wish to break existing users. Since the function does nothing but call `launchApp`, there is little maintenance upkeep to keeping it.
I remove the line from documentation that it will be removed. It remains deprecated, however.

If you'd like, please submit a PR with removing `relaunchApp` from the docs and test suite. It would be greatly appreciated.

Thanks
