### ISSUE TITLE
View Hierarchy dump is an impediment to adoption

### ISSUE THREAD

**Issue by seantimm** [wix/Detox#1227]
I know this request has already come in.  I appreciate your desire to see people adopt clean view architecture.  However, you're getting these requests to suppress the view hierarchy because people are dealing with existing solutions that are already in a bad state.  It takes time and resources to move, and it's not always easy or quick.

I'm at a loss as to why you wouldn't want to add support to suppress the view hierarchy (or at least allow someone else to make a pull request to do so).  The current behavior is a deterrent to adoption for projects that don't meet your standards.

Why not make it easy?  If you really want to impose your thoughts, provide an option, but show a warning during each run "You're currently suppressing view hierarchy.  This suggests that your view hierarchy is too complex.  You should really clean this up, so you can get the benefit of our view hierarchy dump."

**Comment by LeoNatan** [comment]
I don't like the particular tone used in this issue. We are an opinionated bunch, and our opinions come with the intention of having a better app ecosystem. As with any **free and open source**, users who disagree with the maintainers view points are welcome to fork the project or use a different one.

We've always been conflicted on this one, as it seems there is a real pain here, but it seems to be a self inflicted one (by the app developer), by using bad frameworks (such as React Navigation) which bloat the view hierarchy to no end, cause issues with Detox (duplicate views because the same testID is used in several screens and they are ALL loaded in the hierarchy), slow down devices and waste CPU and battery. People's tests fail on bad application environments and they come here to complain that Detox is broken. If the hierarchy is hidden, it is another layer of obfuscation that we'll have to deal with when users' tests fail. And I say that, fully expecting that some teams internally here will probably also enable this "feature" you ask for. This is why we are reluctant. Can't enable or abuse a bad feature if it doesn't exist. If it also makes people improve their apps due to frustration, seems to me like a win-win for both parties.

**Comment by noomorph** [comment]
@LeoNatan, could you also remind what the issue with adding a flag to control this behavior was? I remember it involved changes on the native side, but was there anything more to it?

**Comment by seantimm** [comment]
Thanks for the response.  It's in line with where I expected your thinking was, but I opened the ticket as a plea to reconsider and think about the impact it has on adoption and use.  I get that this is open source and free, and it's why I spend a lot of time trying to figure out my own problems before I reach out for help... maintainers have enough to worry about.  It's also why I mentioned accepting a pull request to add the option to suppress, but my assumption based on current responses to this issue were that it would be summarily dismissed. 

The tone you're picking up on is nothing other than frustration that such a great project would choose this hill to die on.  It seems like such a crazy thing to fork a project on or insist people move on to some other option.  Our team has had Detox in our project for quite a while, and it was super easy to find out when / which tests were failing when failures were introduced and deal with them locally because the failures were listed in clear English (test names) that we could drill into and identify the problem... right up until the release that suddenly doubled the size of our build logs during large test failures and made it impossible to figure out which tests were failing locally without logging the results to disk and searching the file for "All Tests".

We do use React Navigation (as I'm sure many others that have brought up this issue do).  The ability for us to deliver updates live via CodePush currently outweigh your thoughts on the bloat of the View hierarchy.  It's entirely possible there's another way to accomplish these same things, but those will be weighed by the pressing needs of the business as to when we could possibly switch over, and it will take time to do so.

What I'd really rather see is a separate disk dump of the View Hierarchy for any failing tests.  Often in the case of a failing test, I know what the problem is by what changed in the code and just need to know the name of the test that failed (that used to be so cleanly listed at the end of a build).  It's far less often that I need to refer to the view hierarchy to figure out how to fix things, but that's the most prominent thing in failures now.

**Comment by LeoNatan** [comment]
Make a PR and I'll accept it.
The hierarchy is obtained here: https://github.com/wix/Detox/blob/e98e2f36ca90a3a19178a0ba16301cfd8e3d0cd2/detox/ios/Detox/TestFailureHandler.m#L20
A PR would check some launch argument's existence and not include it if the argument exists.

Thanks

**Comment by seantimm** [comment]
Thanks for the pointer!  I started looking at it but got stuck on getting tests to pass after initially pulling down, so I'll work on making sure I have a clean environment and then start seeing what I can do here.

**Comment by LeoNatan** [comment]
After an internal discussion,  we have decided not to support this feature. Sorry.
