### ISSUE TITLE
Integration with `jest`

### ISSUE THREAD

**Issue by grabbou** [wix/detox#143]
Hey,

Thanks for the library! I've managed to set it up with `jest` since that's the default runner in React Native.

I was wondering whether:
a) we should use `jest` by default since it's default for React Native (might be tricky to integrate with Wix infrastructure)
b) add an example to repo
c) write a blog post

I guess `c` will happen anyway tomorrow :)

**Comment by DanielMSchmidt** [comment]
Would love to see some documentation around it and an example, that would be cool 🎉

**Comment by talkol** [comment]
No real Wix-related objections with `jest` by default.. We actually use `jest` internally for all our unit tests now.

The only reason I waited with changing the defaults is because we don't have the runner requirements yet for running iOS and Android in parallel. For example, assume you want to mark some tests for iOS and some tests for Android. Maybe even use the RN convention of file extensions when you want to split behavior per platform. Once we have the requirements we'll need to see which runner supports them best and then we'll probably adopt it as the default

Awesome stuff though! Blog post will be amazing!

**Comment by rotemmiz** [comment]
The main difference between runners like Mocha or AVA to Jest is that they don't an expectation library bundled inside, they are solely test runners.
Detox has it's own `expect` object, which will override Jest's `expect` when running `detox.init()`. 

To sanely support Jest, and not confuse users, we would need to provide a way to control the the globals we export, maybe a different init function that doesn't do that, and let users import/require `expect` as they see fit.

**Comment by mobinni** [comment]
Hey there, I was able to setup Jest usage as well although it seemed a bit hacky. https://github.com/rangle/react-native-example/pull/19/files#diff-33b5654ffcc43d384eab9191d8b93768

**Comment by grabbou** [comment]
@rotemmiz the way I did it so far is that, inside `init` file of Jest, I detect whether I am running `__tests__` folder or `__e2e__` folder. If latter, I init `detox`. Developers are expecting Jest `expect` to be modified in the context of that folder. So as long as it's `e2e` folder, Jest becomes just a runner.

The benefit is that it's integrated testing environment and less dependencies to please my json

**Comment by samin** [comment]
@grabbou do you have an example?

**Comment by AlanFoster** [comment]
@samin I couldn't find the blog mentioned - but I did find a repository:

https://github.com/grabbou/react-native-detox-example

**Comment by rumax** [comment]
Maybe it would be even better to avoid integrated test runners at all? And instead: `detox` provides `init`, `relaunchApp`, `by`, `element`, etc. and it will be possible to use any runner.

**Comment by AlanFoster** [comment]
I am currently integrating detox onto a project right now; and everything worked great. We have a slightly naming convention for our test folders, i.e. `tests` and `e2e` rather than `__tests__` and `__e2e__`, but this should still be useful for someone.

Updating the package.json file to setup jest with a particular framework setup file for unit/e2e tests:

```js
  "scripts": {
    // Splitting out 'test' for unit tests by default, and 'test-e2e' for detox
    "test": "jest tests/.*\\.spec\\.js$ --setupTestFrameworkScriptFile=./jest/setup-unit-tests.js",
    "test-e2e": "jest e2e --setupTestFrameworkScriptFile=./jest/setup-e2e-tests.js",
  },

  // Nothing additional required here - added only for visibility
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|tcomb-form-native|react-navigation)"
    ]
  },

  // Adding the detox config
  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/example.app",
        "build": "xcodebuild -project ios/example.xcodeproj -scheme example -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
    }
  }
```

The `./jest/setup-e2e-tests.js` file looks like:

```js
import detox from 'detox';
import packageFile from '../package.json';
const detoxConfig = packageFile.detox;

jasmine.DEFAULT_TIMEOUT_INTERVAL = 120000;

beforeAll(async () => {
  await detox.init(detoxConfig);
});

afterAll(async () => {
  await detox.cleanup();
});

beforeEach(async () => {
  await device.reloadReactNative();
});
```

As well as dropping in a basic test within `e2e/example.spec.js`:

```
describe('Example', () => {
  it('should have welcome screen', async () => {
    await expect(element(by.id('welcome'))).toBeVisible();
  });
});
```

That was everything required to get jest + detox working; Just kick it off with `npm run test-e2e` and then the simulator etc opens up.

**Comment by grabbou** [comment]
@AlanFoster yeah, I ended up not writing an article, but made an example in the repository. @rotemmiz I would be happy to chat the requirements in order to get such integration working w/o any hacks - hit me up on Slack.

**Comment by IkerArb** [comment]
How can I use the detox test --reuse command with jest? I don't want the app to be reinstalled each time but I don't know how to use this flag with jest

**Comment by stereodenis** [comment]
@AlanFoster how to choose detox configuration?

**Comment by isnifer** [comment]
@stereodenis `detox test -- configuration ios.sim.release` for example :)

**Comment by stereodenis** [comment]
@isnifer it's for detox cli, but I wanted to know about jest

**Comment by isnifer** [comment]
@stereodenis I don't know how are you starting your tests with jest.
But I did simple `omitBy` to select configuration:
```js
// ...
import { omitBy } from 'lodash'
import pkg from '../../../package.json'

const {
  PLATFORM = 'ios',
} = process.env

export default async function runnerDetox() {
  const configurations = omitBy(pkg.detox.configurations, (value, key) => (
    !key.startsWith(PLATFORM)
  )
  await detox.init({ configurations })

  // ...

}
```

My `package.json`
```json
"detox": {
  "configurations": {
    "ios.sim.release": { ... },
    "android.emu.release": { ... }
  }
}
```

Sure, you can create something like this

**Comment by MoOx** [comment]
Maybe a simple section in the doc to say that there is nothing special to do according to https://github.com/wix/detox/issues/143#issuecomment-318762789 (except of normal jest usage?)

**Comment by tengrobert** [comment]
I would like to know the solution to the same problem as @IkerArb mentioned. Has anyone found yet? : )

**Comment by dariocravero** [comment]
@tengrobert @IkerArb the problem is that `reuse` isn't an API configuration but a CLI argument https://github.com/wix/detox/blob/d882d0e74174dfece282af66d91ad34b747fb770/detox/src/devices/Device.js#L28. Unfortunately jest fails if you use an unrecognised argument in the CLI, otherwise, you could just add `--reuse` to jest.

That line could be replaced by `if (!argparse.getArgValue('reuse') || this._deviceConfig.reuse) {` and then the config would look like:

```
  // Adding the detox config
  "detox": {
    "configurations": {
      "ios.sim": {
        "binaryPath": "example.app",
        "type": "ios.simulator",
        "name": "iPhone 7",
        "reuse": true
      }
    }
  }
```

That's the simplest without changing the code too much. Ideally, a global `reuse: true` sitting at the level of `configurations` would work better as it would be closer to how the CLI is instructed to work.

I don't have time to do a PR now, so feel free to submit one if everyone's happy either approach.

**Comment by sibelius** [comment]
```jsx
jest-haste-map: watch error:
  SyntaxError: Unexpected string in JSON at position 4089
    at JSON.parse (<anonymous>)
    at module.exports (app/node_modules/metro-bundler/node_modules/jest-haste-map/build/worker.js:65:29)
    at Promise (app/node_modules/metro-bundler/node_modules/jest-haste-map/build/index.js:492:7)
    at Promise (<anonymous>)
    at _workerPromise.message (app/node_modules/metro-bundler/node_modules/jest-haste-map/build/index.js:491:7)
    at HasteMap._processFile (app/node_modules/metro-bundler/node_modules/jest-haste-map/build/index.js:404:42)
    at changeQueue.then (app/node_modules/metro-bundler/node_modules/jest-haste-map/build/index.js:705:32)
    at <anonymous>
```

anybody got this error?

**Comment by sonianin** [comment]
Is there a way to choose configuration when running tests with Jest?

**Comment by DanielMSchmidt** [comment]
@sonianin Not yet documented, but you could use environment variables to set the config and choose the right config by filtering the list of configurations by it in the `setupTestFrameworkScriptFile`, like in [the solution](https://github.com/wix/detox/issues/143#issuecomment-329115235) @isnifer has shown
