### ISSUE TITLE
Refactor apk build path to not include architecture in its flavors

### ISSUE THREAD

**Issue by ayelenmarie** [wix/Detox#1575]
Hi guys! I'm opening this enhancement request that I think will be very useful for Android developers and QAs.

**Is your feature request related to a problem? Please describe.**
Upon the new Play Store requirements for uploading different .apk for every architecture available in our app, we've encountered an issue while trying to test a project that deals with this. 
After running `detox build -c android.emu.debug` successfully, our `detox test -c android.emu.debug` fails and leaves us this error:

```  
Error: '.../mobile/android/app/build/outputs/apk/androidTest/developmentX86/debug/app-development-x86-debug-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest' ?
```
You can see that Detox is trying to access an APK for x86 in a folder that does not exist (developmentX86). This is because it's treating the architecture as a flavor. 

**Describe the solution you'd like**
Since builds for Android testing don't need to specify its architecture version, it would be great if Detox could just not include them when trying to make flavors for its `androidTest.apk`, as `APKPath.js` does when slices all different parts of the `originalApkPath`.

**Describe alternatives you've considered**
In `APKPath.js`, if we refactor line 7 in `getTestApkPath(originalApkPath)` to replace all possible architecture combinations into `""`, we could make flavors that don't have those, eliminating the wrong path that Detox tries to find when running tests:

```
    const originalApkPathObj = path.parse(originalApkPath.replace(/x86\w*-/g, ''));
```
This should solve this problem as I've already tested it as well and it works with the two possible combinations of architecture: x86 and x86_64.

**Additional context**
Our Android configuration for Detox in the project in question:

```
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/development/debug/app-development-x86-debug.apk",
        "build": "cd android && ./gradlew assembleDevelopmentDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.emulator",
        "name": "Pixel_2_API_28"
      },
```

Detox version used: ` "detox": "13.3.2" `

I hope I explained myself well enough. I'll send a PR with the refactored line and the corresponding unit test as well. Just let me know if you need anything else.

Thanks!

**Comment by rotemmiz** [comment]
Hey @ayelenmarie, 

I think that there are a few things that need to be cleared, since I'm not entirely sure how Detox fails to resolve the testApk path.
1. Google Play requires uploading different apks for each architecture? I didn't see that requirement anywhere (maybe I missed something) What I  do know is that Google Play now requiers uploading apks that support 64 bit, but that doesn't mean it needs to have multiple APKs, in fact you can upload [app bundles ](https://developer.android.com/platform/technology/app-bundle) to make the upload process much simpler.
2. How did you separate your architecture flavours in your gradle config? If you still want to use abi-splits (which I don't really recommend, use app bundle instead), you can set to have a split APKs and add a universal apk to include all abi architectures.
3. The fix that you proposed makes wrong assumptions that you would want to test a non x86 apk. so if you do abi-splits (which again I strongly discourage) It will work on devices (which usually have arm64-v8a architecture), but will not work on Emulators.
4. If you still have a problem, you can always set `testBinaryPath` in your config file explicitly.

**Comment by ayelenmarie** [comment]
Hi @rotemmiz, 

Thanks for your comments! We currently use abi-splited apks, but we will read more about app bundles for sure! In the meantime, we will try setting the `testBinaryPath` and see if that works it out for us. I'll get back to you if anything.

**Comment by mnzaki** [comment]
I am facing this issue as well and have resorted to disabling ABI package splitting for debug builds and running tests on debug only.
