### ISSUE TITLE
Feature Request: Monitor & block http calls externally

### ISSUE THREAD

**Issue by yedidyak** [wix/Detox#1635]
**Is your feature request related to a problem? Please describe.**
Generally when running e2e tests, you want to either run against a real server, or mock *all* of your external calls. In the second scenario, it would make sense for the external test runner to monitor IO requests, rather than extra code that runs on the device.

**Describe the solution you'd like**
I would like there to be a way to both monitor what network requests were generated during a test run, and to block all requests except to a whitelist of localhost + specific other domains. This should be set per test suite or specific test.

**Describe alternatives you've considered**
It would be possible to set this up on device by swizzling `fetch` or similar, but this would mean extra device side code specifically for tests. That is counter to the principle of having the tests run against as close to production code as possible.

**Additional context**
Talk to me :)

**Comment by LeoNatan** [comment]
In order to monitor, you can already do it. 

https://github.com/wix/Detox/blob/7f8b563499e0f8265b020d583cb1dbaf5d8d1328/docs/APIRef.DetoxCLI.md#test

Use the `--record-performance all` command-line argument. This will create a Detox Instruments recording, which you can use the Detox Instruments app or its command-line utility `dtxinst` to see the network requests.

Regarding the proxy, this sounds like a big development effort, and I am not sure it can be implemented well in the general case. On iOS, it's somewhat possible to mitm client requests and forward or block them according to a ruleset. That's for "norma" HTTP requests. Other HTTP requests cannot be caught at all, such as out-of-process `WKWebView` (and others) requests. Other types of connections, such as sockets, cannot be caught easily and the OS API surface is rather wide, so it's not feasible to swizzle all that. On Android, I'm not even sure HTTP requests can be easily captured without replacing the entire HTTP stack.

Because a solution like this, I think, should be tailor-made for the app that needs it, I still think the client-side solution for this use-case is the best one. These solutions should not sit in production code. RN has its mocking facilities, native has Xcode- and Gradle-level solutions; those should be used to facilitate the solution. In this way, an app developer, who is (optimally 🙃) fully aware of their app, can produce a solution that works with the API their app is using (swizzle WKWebView directly, swizzle the particular API they are using for sockets, etc.).
