### ISSUE TITLE
Take screenshot after test failure, before afterEach is executed

### ISSUE THREAD

**Issue by viktorijasujetaite** [wix/Detox#1661]
It is common to put additional logic in `afterEach` step (to return to primary state, make additional repetitive checks, etc). 
With current implementation, when the test fails, `afterEach` is being executed and only THEN screenshot is taken. It means that other screen could be opened already, so screen where bug happened is not visible anymore. This way it is harder to analyze bug failures, as you do not have corresponding screenshot.

*Please* implement taking screenshot at the start of afterEach statement.

**Comment by LeoNatan** [comment]
This is probably a bug, rather than enhancement. Failing screenshots need to be taken as early as possible.

**Comment by LeoNatan** [comment]
https://github.com/wix/Detox/blob/81c8e1b7e054552d2c4f544e6cde9e843dc32bc4/detox/src/artifacts/screenshot/ScreenshotArtifactPlugin.js#L30

I am assuming that flipping these two lines will do the trick.

**Comment by noomorph** [comment]
It will not do the trick. And it is not a bug.
The requested functionality needs extra enhancement to the test runner adapters and detox artifacts lifecycle.

`afterEach` in its current understanding should be left as-is because it still represents a valid case for video recordings. Video recording should be finished later, not sooner, even if it is a failing test. Moreover, if an error happens inside `afterEach`, we also cover this case.

Either we should strive to add a lifecycle event `onError`, or a sort of  `afterEachImmediate`. Then we could map the screenshotter to that more satisfying event.

**Comment by LeoNatan** [comment]
Bug in design is still a bug. The screenshots are useless in this case. Screenshots should be taken as close to failure point as possible.

**Comment by noomorph** [comment]
Whatever, the issue is accepted.

**Comment by noomorph** [comment]
The support for `error.png` screenshots will come to Detox + `jest-circus`.

**Comment by noomorph** [comment]
The feature will appear in `detox@16.8.0`.
