### ISSUE TITLE
--debug-synchronization not working on Android

### ISSUE THREAD

**Issue by j320** [wix/Detox#1788]
I'm trying to debug some extra waiting issues I'm facing on Android by executing: `detox test --debug-synchronization` or `detox test --debug-synchronization 20` and there's no extra logging happening. I've used this command a while ago while I was in Detox version 13.4 I think and it worked, now that I'm on the latest is no longer working.

**Environment:**
 - Detox: 14.7.1 first and 14.8.5 after upgrading

**Comment by rossjohnsonMP** [comment]
is this accepted as android only or ios and android? as soon as i upgrade above 17.5.0 --debug-synchronization is broken on ios

**Comment by Kilawuyiek** [comment]
The --debug-synchronization flag is used to enable extra logging for synchronization issues in Detox. It is used for debugging purposes and it is supposed to provide more information about the state of the test environment.

It seems that this flag is not working on your Android environment, even though it worked on an older version of Detox.

This could be caused by a number of reasons, such as:

The flag has been deprecated or removed in the newer version of Detox you are using.
There is an issue with the Detox configuration in your project
There is a bug in the current version of Detox you are using.
It's recommended to check the Detox documentation to ensure that the flag is still supported and how to use it. It's also recommended to check the release notes of the version you are currently using to see if there are any changes related to the --debug-synchronization flag[.](https://namecombinertool.com/)

You can also try downgrading to the version of Detox in which the flag worked for you and test it again.

You can also try to run the test in verbose mode by passing the -v option to the detox command line. Like this:
detox test -v
It's also recommended to check the Detox issues page to see if there are any reported issues related to the --debug-synchronization flag and if there's a workaround.

**Comment by d4vidi** [comment]
@Kilawuyiek debug-sync should definitely work on Android in Detox 20 (latest). Please double (triple) check what you're saying.
