### ISSUE TITLE
Log artifacts no longer have stdout/stderr of the launched app

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#1867]
### Description

The logs produced with the current iOS logs implementation have no stdout/stderr of the simulator, hence critical information is missed (e.g. `console.log()` contents in React Native applications when debugging).

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

1. Add `console.error("THIS_MESSAGE_SHOULD_APPEAR")` to `SanityScreen.js` inside Detox test app.
2. Build the release version with `npm run build:os`.
3. Run `detox test -c ios.sim.release --record-logs all`.
4. Examine the `process.log`. There won't be `THIS_MESSAGE_SHOULD_APPEAR` in the `process.log`.

This issue is a regression caused by f7d08f567db9d1a7dc121dfd56f41d02ab390df8 (PR https://github.com/wix/Detox/pull/1428)

#### Expected behavior

I should be able to see `console.log` messages inside device logs taken with `--record-logs`.

#### Screenshots

This message will be missing in `artifacts/ios.sim.release */Sanity */process.log`:

<img width="640" alt="Screen Shot 2020-01-21 at 1 27 02 PM" src="https://user-images.githubusercontent.com/1962469/72801261-cc8c8480-3c51-11ea-9caa-06c41fafa727.png">

#### Environment (please complete the following information):

 - Detox: 15.1.3
 - React Native: 0.60.5
 - Node: 12.10.0
 - Device: iPhone 11 Pro
 - Xcode: 11.2.1
 - iOS: 13.2.2
 - macOS: 10.14.6

**Comment by LeoNatan** [comment]
The issue is in the RN logger behavior. Instead of using modern logging facilities, they are using fprintf directly to stderr, which isn't caught by the system logging system. Not sure what the proposed solution should be? We **cannot** stop collecting the system log, we cannot revert to the old system. We could swizzle somehow the RN logger, but that sounds very error prone, especially if user provides their own logging methods.

I think the only viable solution to this is to open an issue in RN, which I've done: https://github.com/facebook/react-native/issues/27863

**Comment by LeoNatan** [comment]
Solved in RN master. So this will sort itself with time. For now, there is a solution internally.
