### ISSUE TITLE
Using detox in a browfield context

### ISSUE THREAD

**Issue by mfrachet** [wix/detox#187]
We're actually working on a React Native application in a brownfield context.

It supposes that the React Native application is started inside of a native application, and so in IOS / Android.

We have discovered Wix Detox during React Europe 2k17 and made some tests in a greenfield context, with great feelings.

Actually, we're looking for a solution to use Detox in a brownfield context, and we're wondering if it does exist anything to make this work ?

Here's a common scenario :

- Start the native app
- Click de "React Native App" button
- Assert that the React Native App title is visible on the screen

The main problem is to locate the React Native App (that cannot be launch out of the box due to native bridges) and access it.

Do you have that kind of information in your box ? Or any future plan (where we could eventually help ?)

**Comment by LeoNatan** [comment]
I am not sure I understand the problem here.

If you give your UI elements values in `accessibilityIdentifier`, you can use Detox to discover those elements and perform actions on them. In fact, Detox is implemented in such a way to allow for purely native or mixed apps. Detox installs its own set of idle resources for Earl Grey, which we use internally, and so we can support both.

In your case, if you give you RN button an identifier, and use `expect(element(by.id('MyRNButton'))).toExist();` or `await element(by.id('MyRNButton')).tap();`, it should work.

**Comment by mfrachet** [comment]
Thanks for your answer.

My question was more " How to access my RN app, inside a native app, using Detox ? "

**Comment by LeoNatan** [comment]
I don’t understand what you mean by “access”. RN views are `UIView` objects living in the same hierarchy as your native app.
