### ISSUE TITLE
setColumnValue() not working with Picker from @react-native-community/picker

### ISSUE THREAD

**Issue by j320** [wix/Detox#2031]
### Description
Picker is going to be extracted from react-native core (there's even a warning about it now) and will have to be imported from @react-native-community/picker. 

setColumnValue() at the moment still works when importing Picker from react-native core but not when importing it from @react-native-community/picker which should do as people will be moving there especially with the deprecation warning.

When importing from @react-native-community/picker, it always returns 

`"UIPickerView does not contain desired value!`

Note: I've noticed that the Debug View Hierarchy now returns RNCPicker rather than RCTPicker.

**Comment by LeoNatan** [comment]
Please post the full error and the hierarchy dump you are getting. Thanks

**Comment by LeoNatan** [comment]
https://github.com/wix/Detox/blob/6321de79973ef652469c3f7a9cc1c70d0c293f78/detox/ios/Detox/GREYMatchers%2BDetox.m#L175

Probably the issue is here.

**Comment by LeoNatan** [comment]
The issue is here:
https://github.com/wix/Detox/blob/6321de79973ef652469c3f7a9cc1c70d0c293f78/detox/ios/Detox/ReactNativeSupport.m#L225

I've added this hack for React Native, but I am not sure I want to add it for the "community". Please open an issue with the "community" project to fix their implementation to set both the delegate and data source of the picker view.

**Comment by j320** [comment]
So when the Picker is removed from react-native this function will stop working? 
I don't think I have enough knowledge on how this works in order to open an issue for them to fix it.

**Comment by LeoNatan** [comment]
It's not a problem of Detox. The issue that the implementation is broken. Detox will continue to work with **any properly set up `UIPickerView`**. It was broken for RN, and is broken now for the "community", because all they did was copy paste. If they fix it, it will start working again. 

The issue is here:
https://github.com/react-native-community/react-native-picker/blob/101f272af0e2de57c211f465c81a2c061c72ba4a/ios/RNCPicker.m#L25

As you can see, the delegate it set up, but not the data source. The data source is necessary for the picker view to know how many components (columns) it has. There is some undocumented behavior (= can change at any moment) that if the picker view does not have a data source, the question of number of components is sent to the picker view itself. The solution is to set the data source to be the picker view itself, just like they set the delegate.

**Comment by j320** [comment]
I see what you mean. However if it's broken in current RN as well, how come setColumnValue() still works there?

**Comment by LeoNatan** [comment]
We've added a hack a long time ago to work around this in Detox. But I don't want to add this hack for a "community" project. It should be much easier to fix these issues now, which is why these components are moved to "community". Please open an issue with the project.
