### ISSUE TITLE
Type text to currently focused input

### ISSUE THREAD

**Issue by jlongster** [wix/detox#210]
The `typeText` action requires an element, but it would be nice to just text into any element that is currently focused. That way we can test certain workflows where the input should autofocus. Is there a way to do this already?

**Comment by LeoNatan** [comment]
Could you please elaborate? Do you mean sending keyboard clicks in the responder chain? What are you looking to achieve/test? As I see it, this can most useful for testing iPad keyboard shortcut support, such as CMD+C, CMD+V, etc.

**Comment by Eyesonly88** [comment]
@abdulkhaliquem9 adding a testID would find the `inputText` even if it was autofocused. However, since the library you are using doesn't have a `testID`, if I were you, I would either implement the component from scratch without needing the library or just fork the library and add a `testID` to make it easier but yeah not ideal.

**Comment by abdulkhaliquem9** [comment]
@Eyesonly88 got a solution for this issue on Android. 
`await element(by.type('android.widget.EditText')).typeText('08902\n');`
Currently Detox test case fails if we pass 'TextView', and throws error to pass the full class name.
