### ISSUE TITLE
Enhancement on Matcher / Actions with element 

### ISSUE THREAD

**Issue by baopn97** [wix/Detox#2186]
**Is your feature request related to a problem? Please describe.**
I'm currently have an issue with waitFor().whileElement(), for scrollElement i would like to suggest to put find with index for scroll element like this:
`await waitFor(element(by.text('Some Text'))).toBeVisible().whileElement(by.type('RCTScrollView').atIndex(2)).scroll(500, 'down');`
And 1 more suggestion for finding elements, is to use` by.containsText()` instead of `by.text()` because in case of RN app have huge amount of elements, there is no way to mark specified ID for them, so the best solution is to find them depends contains text

**Comment by LeoNatan** [comment]
Your `atIndex()` example should work, but it's a bad idea. Likewise for text. What does it mean "no way to mark specified ID". Of course there. And if you are using some third party framework, complain there. Any proper framework should allow for accessibility and testability.

**Comment by baopn97** [comment]
@LeoNatan I'm using only JS Detox for UI test, but finding an element with exact content is not ideal, many mobile applications have parameterized elements and auto-generated from one components into multiple elements, so in that specified case we cannot find the exact element.

**Comment by raldred** [comment]
@baopn97 i'd suggest you consider writing tests using enzyme for specific assertion like your example.

**Comment by iradkotton** [comment]
I am also facing the same issue with [ActionSheetIOS](https://reactnative.dev/docs/actionsheetios)

My code:
```js
await waitFor(SOME_ELEMENT)
    .toBeVisible()
    .whileElement(by.type('_UIInterfaceActionRepresentationsSequenceView').atIndex(0))
    .scroll(500, 'down');
```

Error:


![image](https://user-images.githubusercontent.com/70887949/109949923-a3f40c80-7ce4-11eb-97c4-6e305132daff.png)

**Comment by noomorph** [comment]
@iradkotton , you can't use `.atIndex` on `by.*()` matchers.

**Comment by iradkotton** [comment]
> @iradkotton , you can't use `.atIndex` on `by.*()` matchers.

Yes I understood that, I was trying it still since @LeoNatan commented that @baopn97 code should have worked but it doesn't.


> Your `atIndex()` example should work, but it's a bad idea. Likewise for text. What does it mean "no way to mark specified ID". Of course there. And if you are using some third party framework, complain there. Any proper framework should allow for accessibility and testability.

My issue is with using whileElement and match the element together with the [.atIndex](https://github.com/wix/Detox/blob/66ea55ad1616bf1147de0efdee5181c462d9e62f/docs/APIRef.Matchers.md#atindexindex) matcher

And since react-native doesn't expose an option to set testID to an ActionSheetIOS component the best option I found to scroll and ActionSheetIOS was to use the .atIndex matcher.
@noomorph is there a way to use .atIndex together with [.whileElement](https://github.com/wix/Detox/blob/66ea55ad1616bf1147de0efdee5181c462d9e62f/docs/APIRef.ActionsOnElement.md#whileelementelement)?

**Comment by noomorph** [comment]
@iradkotton, no, there is not at the moment. For some reason, it has not been implemented. 🤷
**Please create an issue with a feature request and I'll try to look into it next week.**
And let's keep this discussion inactive so I don't have to lock it explicitly.
