### ISSUE TITLE
Ability to mock providing QR codes to emulator

### ISSUE THREAD

**Issue by Overtorment** [wix/Detox#2291]
**Is your feature request related to a problem? Please describe.**
Example: I have a lot of userflows that depend on users scanning QR codes with their devices. 
(sometimes QR codes are _animated_, like, several frames, to transmit more data).

**Describe the solution you'd like**

It would be awesome if I could provide detox an image with QR code, and this image could be like, in front of a camera of emulator, so next time my app launches camera and looks for QR - it will scan this exact QR.

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by LeoNatan** [comment]
I am not familiar with any OS-standard ways of scanning QRs. So this cannot really be achieved in Detox. You should have this mocking as part of your test logic, and perhaps you can open sources it so that people get ideas how to do it in their apps. But I just don't see how this can be done in a general-purpose way.
