### ISSUE TITLE
Detox keeps on creating lots of iOS simulators 

### ISSUE THREAD

**Issue by alexmngn** [wix/Detox#2394]
I'm experimenting an issue where I see Detox creating a lot of new iOS simulators for every execution and I'm trying to understand what can be causing this.

In my configuration I'm setting the "iPhone 8" device which is already in the list of simulators. But Detox keeps on creating more and more of those.

Would you have any idea what can be causing this problem?

I run Detox on my project with the following configurations:

```json
{
  "rootDir": "../",
  "setupFilesAfterEnv": ["./detox/init.js"],
  "preset": "react-native",
  "testEnvironment": "detox/runners/jest/JestCircusEnvironment",
  "testRunner": "jest-circus/runner",
  "reporters": ["detox/runners/jest/streamlineReporter", "<rootDir>/node_modules/jest-junit"],
  "transform": {
    "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
  },
  "verbose": true,
  "maxWorkers": 6
}
```
```json
{
  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/MyProject.app",
        "build": "xcodebuild -quiet -workspace ios/MyProject.xcworkspace -scheme MyProject -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build | grep -A 5 error: | xcpretty",
        "type": "ios.simulator",
        "name": "iPhone 8"
      }
    }
  }
}
```

And execution is done with the following:

```
detox test -c ios.sim.debug "./tests/" -l --loglevel=error --take-screenshots=failing --workers="6"
```

This is the list of simulators created to give you an example:

![Screenshot 2020-10-08 at 14 18 39](https://user-images.githubusercontent.com/4203845/95464291-a76fab80-0971-11eb-82fb-eca761757056.png)

Thank you.

**Comment by noomorph** [comment]
Detox creates a new simulator whenever it sees that all the matching ones are listed in the lock file (i.e., they are busy), see `~/Library/Detox/device.registry.state.lock`.

If you have this much maxWorkers (6), and you had unsuccessful suites where `detox.cleanup()` had failed to finish, there's a high chance that with every next test suite file, Detox will be seeing that there aren't available simulators and it will try to create one more.

It might be a design bug, actually, but most likely we're going to fix that only when we move to leveraging globalSetup/globalTeardown phases in Jest, to allocate simulators first, and then just re-use the existing ones. Not sure if we can remedy this at this very moment in October.

**Comment by Grohden** [comment]
My 2 cents on this one:

I'm running detox using intellij run button, and often I kill detox to re-run... detox ends up not deleting the `.lock` file it created (probably because it was killed improperly), so almost every run it was creating new emulators.. 

So for my jest run button I've made a external tool that runs `rm -rf` on that file and put it to run before every launch.. it solved for me

<img width="855" alt="Screen Shot 2021-08-03 at 10 52 39" src="https://user-images.githubusercontent.com/7496871/128027900-d2ab7303-6dc8-441e-9c6e-9ca8a9337249.png">
<img width="802" alt="Screen Shot 2021-08-03 at 10 54 09" src="https://user-images.githubusercontent.com/7496871/128027688-df2bce74-741f-4209-b4a2-fe1ea8e6bf2b.png">

`e2e-delete-detox-locks.sh` contents:
```
if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Cleaning iOS lock files"
  rm -f ~/Library/Detox/android-device.registry.state.lock
  rm -f ~/Library/Detox/device.registry.state.lock
  echo "Detox iOS lock files deleted"
else
    echo "TODO: detox cleanup in linux"
    exit 1
fi
```

**Comment by d4vidi** [comment]
Thanks @Grohden, this is in fact what we do when working on Detox and executing from the IDE 👍🏻
