### ISSUE TITLE
Call supported EarlGrey and Espresso matcher APIs in runtime

### ISSUE THREAD

**Issue by DanielZlotin** [wix/Detox#251]
#### Description
Instead of manually adding any and all matcher APIs like [this](https://github.com/wix/detox/issues/246) request, maybe we can add functionality to detox API to call any supported matchers from JS in runtime.
For example, something like `expect(...).toMatch('earlgrey_isClickable')`.

**Comment by isnifer** [comment]
@DanielZlotin already done here - https://github.com/wix/detox/pull/178

**Comment by rotemmiz** [comment]
@isnifer, #178 only exposes an easy way to access `GREYActions` from JS. this is not exposed to the users, it's just a convenient way for Detox developers to add actions to the API (not the API itself).

What @DanielZlotin is asking is a way to use native **[matchers](https://github.com/wix/detox/blob/master/detox/src/ios/matchers.js)**, not **[actions](https://github.com/wix/detox/blob/master/detox/src/ios/expect.js#L46)**, I actually think this is a great idea. Your comment may confuse others.

**Comment by isnifer** [comment]
@rotemmiz ok, removed my previous comment

**Comment by LeoNatan** [comment]
@isnifer I have noticed that you are very active in our issues. While we appreciate your enthusiasm, please try to limit your comments only to cases where you have concrete solution to the issue. Too much chatter in the issue discussion makes it more difficult for us to identify the issue source and assist. Thanks for your understanding.

**Comment by isnifer** [comment]
OK, no problem :)

On Sep 6, 2017 01:08, "Leo Natan" <notifications@github.com> wrote:

@isnifer <https://github.com/isnifer> I have noticed that you are very
active in our issues. While we appreciate your enthusiasm, please try to
limit your comments only to cases where you have concrete solution to the
issue. Too much chatter in the issue discussion makes it more difficult for
us to identify the issue source and assist. Thanks for your understanding.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wix/detox/issues/251#issuecomment-327317788>, or mute
the thread

**Comment by LeoNatan** [comment]
I think this is out of scope. Closing for now.
