### ISSUE TITLE
How to performing actions on browsers/another app/gallery/contacts etc.

### ISSUE THREAD

**Issue by shoumma** [wix/detox#258]
#### Description
In our application we use Facebook authentication. In the login screen there is a button to 'Continue with Facebook' and clicking on that button opens up either the FB app (if available), or safari. Also there are some other places where we need to access the photo gallery. Now we can make the button clicks from our app, but is there any way to make clicks and fill forms when the FB app/Safari comes up?

If we need to mock this process, is there any recommended approach? Also is it possible to select a photo from gallery using Detox?

Would really appreciate any advice or suggestions on these.

**Comment by isnifer** [comment]
About FB - https://github.com/wix/detox/issues/136

**Comment by DanielMSchmidt** [comment]
I think this is not possible in general. As far as I understand it detox and EarlGrey can not interfer with stuff like this. But don't take my word full on this, I am only 80% sure

**Comment by LeoNatan** [comment]
You need to mock the FB/Safari part. This is not supported in Detox.

Regarding photos, if you are using the native `UIImagePickerController`, it should be theoretically possible because that is all in-app, but it should be difficult because I assume there are no `testID` on the views. I suggest mocking that too.

**Comment by shoumma** [comment]
@LeoNatan Thank you for confirming 👍
