### ISSUE TITLE
Time Stimulation for Testing

### ISSUE THREAD

**Issue by heuism** [wix/detox#261]
Hi guys, my current application require testing about the date time and such things. So i wonder if anyone has the experience of dealing with that using detox?

Thanks

**Comment by DanielMSchmidt** [comment]
Thank you for taking the time to file this issue. I did a bit of investigation:
We currently have no way of doing this.

I could not find a thing in `fbsimctl` that could set the time of a simulator. If you are more successful to find a robust (speak no AppleScript) solution I am sure we can add it to detox.

**Comment by LeoNatan** [comment]
This is not an fbsimctl issue. The problem is in the simulator runtime—it does not allow for simulators to have their own time. Instead, they use the same system as the host macOS. I don't think changing the host OS timezone and time settings is acceptable or appropriate, and so will not be part of Detox.

You can go about doing this using mocking. You should mock the method you use to obtain date.

**Comment by heuism** [comment]
Thank2 @LeoNatan  and @DanielMSchmidt for giving thought about this. Thread close
