### ISSUE TITLE
Enhancement: stop locking issues

### ISSUE THREAD

**Issue by badsyntax** [wix/Detox#2684]
**Is your feature request related to a problem? Please describe.**

I'm doing some research on detox, and i'm finding many detox issues are locked. This is hugely annoying. 

**Describe the solution you'd like**

Do not lock issues.

**Describe alternatives you've considered**

**Additional context**

"Blindly" locking issues is an abuse of the lock feature and stifles community engagement. Issues can be closed, and not locked, and this allows for others to continue conversations or provide workarounds. 

What is the reason for locking issues? It's really not clear to me.

**Comment by d4vidi** [comment]
@badsyntax sorry you feel this way. I was not under the impression that we go about locking issue all-too often. I would appreciate some examples, if you don't mind. We typically _close_ issues - through the stale-bot, because many times issue reports tend to stop reporting back, leaving us unable to address the problem. However, that only closes issues - and doesn't lock them...

**Comment by badsyntax** [comment]
hi @d4vidi. firstly i want to apologise for my tone. i felt bad after posting this. thanks for your humble response. 

here's some examples of locked issues: 

- https://github.com/wix/Detox/issues/1016
- https://github.com/wix/Detox/issues/1677

i'm not able to find any recent locked issues, so perhaps this behaviour was changed?

**Comment by d4vidi** [comment]
Hey no problem 🤜🏻 🤛🏻 
Seems like the works of a transitively used bot. I've unlocked the issues you mentioned, in any case.

**Comment by badsyntax** [comment]
Awesome thanks :)
