### ISSUE TITLE
Cant install Detox using yarn

### ISSUE THREAD

**Issue by mhyousefi** [wix/detox#282]
When I run `yarn add detox`, I get the following error:
```
<project directory>/node_modules/.bin/detox: fork: Resource temporarily unavailable
```

However, when I run `nom install detox` afterwards, the error goes away...
I was wondering why Detox can't be installed with `yarn add`.

**Comment by rotemmiz** [comment]
Please add more details for your problem, as stated in the issue template.
Also run yarn add with verbose logging, paste the log here

**Comment by mhyousefi** [comment]
I deleted my `node_modules` directory and then performed `yarn add` to resolve an issue not related to `Detox`. Then I realized that I get, the error mentioned above.
Referring to your documentation, I realized that you instruct installing detox with `npm install`, so I did so and the issue was resolved. I was wondering why this is happening.

As far as verbose logging for `yarn add` is concerned, `yarn add detox --verbose` gives me tremendously numerous lines of logging I hardly think would be useful to detect something 😄

**Comment by LeoNatan** [comment]
This sounds like a yarn issue, Closing

**Comment by MoOx** [comment]
Actually installing detox + detox-cli with yarn is causing the issue. I don't like global cli tool (as it's a pain to manage with teams) so I stupidly installed both (and since I rely in package.json scripts, it's not a problem to use local CLI).
Just removing detox-cli locally (yarn remove detox-cli) and you will be good. It's not required as "detox" package already have a bin)
