### ISSUE TITLE
test-butler-app link is dead

### ISSUE THREAD

**Issue by badsyntax** [wix/Detox#2831]
### Describe the bug

My CI build is failing because the test-butler download URL is returning 404.

### Steps To Reproduce

Try view this url: https://linkedin.bintray.com/maven/com/linkedin/testbutler/test-butler-app/2.1.0/test-butler-app-2.1.0.apk

### Expected behavior

I should be able to download the test-butler apk from the URL provided in the [README](https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md).

**Comment by badsyntax** [comment]
Perhaps this is the correct url? https://repo1.maven.org/maven2/com/linkedin/testbutler/test-butler-app/2.2.1/test-butler-app-2.2.1.apk

**Comment by d4vidi** [comment]
Indeed - newer test-butler version have been uploaded to maven-central instead of bintray, following bintray's announcement of shutting down. In any case, test-butler has been integrated to Detox' `react-native-jest` demo project, and is downloaded regularly in its custom global (Jest) setup [script](https://github.com/wix/Detox/blob/master/examples/demo-react-native-jest/e2e/global-setup.js#L17).
