### ISSUE TITLE
Using Detox to automate native iOS and Android versions of the same app

### ISSUE THREAD

**Issue by ssrinivasKG** [wix/Detox#2859]
Hey guys, Im wondering if having detox tests living in a separate central repository for iOS and Android is a good design pattern. 
The reason for this is we have mostly the same functionality for both the versions of the app and having the tests for both platforms be located in the same place would make sense from a maintenance perspective.

Hoping for thoughts/ideas/concerns regarding the above approach?

**Comment by noomorph** [comment]
That approach can work, but it is more suitable for production tests (with no or very few mock servers and other mocks) rather than anything else. Also, it is going to be not really trivial to keep in sync the app code and the test code: e.g. you are testing a new feature which can be (or not) included into the built app depending on specific version numbers, or you are missing a `testID` on a screen and then you have legwork to add it to both repositories... and so on.

Do you have a React Native app? It just sounds weird that you have different repositories for Android and iOS. A typical React project has them both inside. 🤔

**Comment by ssrinivasKG** [comment]
We're working on native iOS and native Android apps. Hence the different repos

**Comment by noomorph** [comment]
@ssrinivasKG, curious. I thought there were unsolved issues in Detox that prevent from running non-RN apps on Android.

**Comment by ssrinivasKG** [comment]
Oh! I was not aware of the issues. Read the readme.md, Saw this PR https://github.com/wix/Detox/pull/2835 and some example code supporting this.

**Comment by noomorph** [comment]
It is another project, for Java/Kotlin consumers.

The issue for Android is here: https://github.com/wix/Detox/issues/2543 (still open, as of now).

**Comment by ssrinivasKG** [comment]
Thanks for that!!! We were evaluating Detox, but this seems like something that is not yet supported. Any Idea on when this might get prioritized? Really like the idea of native automation that is not Appium and uses Javascript 😅

**Comment by noomorph** [comment]
@ssrinivasKG, well, we have some reinforcement in the person of @jonathanmos (💪 regards to Jonathan) since last month — so I asked @d4vidi in https://github.com/wix/Detox/pull/2835 whether we have some capacity for this summer. Let's move to that discussion. I'm closing this issue since you have an answer that way or another, and it is now a bit duplicating #2835.
