### ISSUE TITLE
Jest advance timers by time

### ISSUE THREAD

**Issue by maykonmichel** [wix/Detox#2897]
Hi, I'm using Detox with jest and my app has a timer developed with `setInterval` that I'd like to skip on my tests. Although I'm using `jest.advanceTimersByTime` it's not working with Detox. Can someone help me?

``` typescript
import {device, element, expect} from 'detox';

describe('Code screen', () => {
  beforeAll(async () => {
    await jest.useFakeTimers('modern');
    await device.launchApp();
  });

  it('should end timer within 15 seconds', async () => {
    const timer = element(by.id('timer'));
    await jest.advanceTimersByTime(15000);
    await waitFor(timer).not.toBeVisible().withTimeout(15000);
  });
});
```

Although my test pass, it takes 15 seconds to finish because I can't skip the timer.

**Comment by noomorph** [comment]
Not possible by design.

**Comment by noomorph** [comment]
This guide is outdated, but the main message is still true: https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md

You need to create a double for one of your code files, with an extra file extension, e.g.: `MyComponent.e2e.tsx` or `MyCompoment.detox-mock.tsx` (or whatever the extension you like) alongside your `MyComponent.tsx`. And make sure that Metro bundler uses your custom extension to pack that mocked implementation instead of a production-facing one.

In your custom mocked implementation, remove somehow your timeouts, and that should solve the problem.
