### ISSUE TITLE
Add getAttributes description to typescript types

### ISSUE THREAD

**Issue by indradeepchowdhury** [wix/Detox#2971]
I could not find getAttributes method in the latest version. I thought getAttributes was supported on both Android and iOS. Please let me know if it has been removed? Are there any alternatives in that case.

**Comment by d4vidi** [comment]
@indradeepchowdhury `getAttributes` is supported and also regularly tested.
What did you mean exactly by "not finding" it? It might be missing from the typescript types - perhaps that got you confused.

**Comment by noomorph** [comment]
Please reformulate the issue to include the actual missing part - TypeScript typings. I think the issue should stay open if it is not a duplicate.

**Comment by indradeepchowdhury** [comment]
@d4vidi Sorry for not being elaborate. Yes that is what I meant :)

**Comment by gabrieldonadel** [comment]
I'm getting `Property 'getAttributes' does not exist on type 'NativeElement'.` when trying to use `getAttributes` on iOS on detox 18.7.1

**Comment by princefishthrower** [comment]
@grgr-dkrk - thanks for this information. Yes, I realized that Detox has since moved to defining types in it's own repository - I've just created essentially the same pull request there. I'd be happy to submit a PR to remove the detox types here, but I'm not sure how reverse-compatible the official Detox types are - maybe I'll just try it and see what people say :)

**Comment by d4vidi** [comment]
@grgr-dkrk no harm, no foul. We'll sort it out end to end asap.
