### ISSUE TITLE
Web View interaction on iOS

### ISSUE THREAD

**Issue by Vannevelj** [wix/Detox#3030]
**Is your feature request related to a problem? Please describe.**
I have an iPad app that displays a Web View of a report. This report contains buttons which send a message to the Web View with some of the data behind that button. The app listens for these messages and loads the data in the actual app.

**Describe the solution you'd like**
I'd like to be able to write a Detox test which taps on a button and then verifies the data was loaded as intended.

**Describe alternatives you've considered**
Since I only need to tap I can try to use this [API](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#tappoint).

**Additional context**
In [18.7.0](https://github.com/wix/Detox/releases/tag/18.7.0) Web View interactions were added for Android. It mentions 

> This functionality is not supported for iOS at the moment and there's no ETA.

While I appreciate this might not be a priority, I also didn't see any open issue around this. I created this so that it can be tracked for updates.

**Comment by Vannevelj** [comment]
Not stale, still interested in this.

**Comment by ShivamJoker** [comment]
Seems interesting will it work with Safari or Chrome too ?

**Comment by antgly** [comment]
@ShivamJoker This would only work with Safari web view content that uses the system Safari view controller (the kind of Safari web view where apps usually show a full screen web page with a Done button in the top left corner - that kind of view is displayed outside of the app sandbox accessible view hierarchy). Chrome on iOS is a Safari web view wrapper that doesn't use system web view controllers and it can't be embedded into other apps; only Safari is available for this on iOS due to Apple restrictions.

**Comment by ShivamJoker** [comment]
So I am guessing it should work on Google ads aka admob too ? Because they are using webview internally, I couldn't select any of the elements by using element by text or type

**Comment by antgly** [comment]
Have you tried using a view hierarchy debugger, such as the one built into Xcode or a tool called Reveal? You might have a view hierarchy that’s blocking interaction. Ongoing animations (usually a big) can also be the culprit as they can interfere with Detox’s expected synchronization if never cleaned up appropriately (as they should be… should be considered a bug otherwise) or mocked out (at worst).

**Comment by guzmanoj** [comment]
Are you guys planning to use [EarlGrey 2](https://github.com/google/EarlGrey/blob/earlgrey2/docs/setup.md) for achieving this?
This is such an important feature. There's a huge enterprise opportunity with the adoption of Ionic. Being able to interact with a Webview would be key for Ionic apps :)

**Comment by asafkorem** [comment]
@guzmanoj generally, we plan to use XCUITest framework directly without EarlGrey for achieving this 🙂

**Comment by pacozaa** [comment]
@asafkorem Hi, I am interested in this issue. Is there any way I can help with this?

**Comment by theaa-zeeshan-khan** [comment]
I am also interested in this issue and am able to help. Is there are updates / timelines to when webview support will be added?

**Comment by d4vidi** [comment]
We're planning to take this after the next major Detox release (v21) - with XCUITest inside

**Comment by asafkorem** [comment]
WebView testing support for iOS released with [v20.19](https://github.com/wix/Detox/releases/tag/20.19.1).
FYI @Vannevelj @Gnarwall19 @ShivamJoker @antgly @pacozaa @guzmanoj @theaa-zeeshan-khan
