### ISSUE TITLE
Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

### ISSUE THREAD

**Issue by combenu** [wix/Detox#3050]
I have created a new Expo app with typescript template and tried to run `detox test`. The app is running as well without any error. but I'm facing the log messages related idle status as following and test was not passing:
```
detox[17848] INFO:  [APP_STATUS] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

One-time Events
⏱ “React Native (bundle load)”
```

Finally, test has been failed with timeout error:
```
detox[16919] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully
 FAIL  e2e/firstTest.e2e.ts (127.329 s)
  Example
    ✕ should have welcome screen (120059 ms)

  ● Example › should have welcome screen

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       7 |
       8 |   beforeEach(async () => {
    >  9 |     // await device.reloadReactNative();
         |   ^
      10 |     await reloadApp();
      11 |   });
      12 |

      at firstTest.e2e.ts:9:3
      at Object.<anonymous> (firstTest.e2e.ts:8:1)
```

### Description
I tried to find out multiple times with drive all of the solutions from stackoverflow, and here.
The app is pretty simple that from scratch. (only App.tsx).
And all of the libraries are latest version.

### Environment

 - Detox: 18.23.1
 - React Native: 0.64.2
 - Node: 12.22.1
 - Device: ios simulator (iPhone 12)
 - OS: Mac OS 10.15.7 
 - Test-runner : `jest-circus`

Here is my `package.json` file
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~43.0.0",
    "expo-status-bar": "~1.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.2",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/detox": "^17.14.3",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "detox": "^18.23.1",
    "detox-expo-helpers": "^0.6.0",
    "expo-detox-hook": "^1.0.10",
    "jest-circus": "^27.3.1",
    "jest-expo": "^43.0.1",
    "react-native-testing-library": "^6.0.0",
    "react-test-renderer": "^17.0.2",
    "ts-node": "^10.4.0",
    "typescript": "^4.4.4"
  },
  "private": true
}
```

And `.detoxrc.json` file
```
{
  "testRunner": "jest",
  "runnerConfig": "e2e/config.json",
  "skipLegacyWorkersInjection": true,
  "apps": {
    "ios": {
      "type": "ios.app",
      "binaryPath": "bin/Exponent.app"
    },
    "android": {
      "type": "android.apk",
      "binaryPath": "SPECIFY_PATH_TO_YOUR_APP_BINARY"
    }
  },
  "devices": {
    "simulator": {
      "type": "ios.simulator",
      "device": {
        "type": "iPhone 12"
      }
    },
    "emulator": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_30_x86"
      }
    }
  },
  "configurations": {
    "ios": {
      "device": "simulator",
      "app": "ios"
    },
    "android": {
      "device": "emulator",
      "app": "android"
    }
  }
}
```

**Comment by suark** [comment]
Seems very similar to what I'm experiencing

**Comment by d4vidi** [comment]
@combenu sorry, but without significantly more info we would not be able to help. Please reopen this as a bug (in either the iOS or Android platforms) and provide all the necessary info - including _device_ logs.

@suark indeed seems similar but I'm inclined to say that it's only because the report is overly shallow and does not really present the root cause.

**Comment by tinmar33** [comment]
Hey, I have the same problem when running a test on Release on iOS (it's working fine on debug). Any idea ?

**Comment by annaostapenko22** [comment]
I am also facing this issue!

**Comment by d4vidi** [comment]
Please try with Detox `19.4.1`

**Comment by sheydarezaee** [comment]
Same issue, and I am on Detox `19.4.1`

**Comment by dnsmob** [comment]
i also have that same issue, and i blame my setup which is a bit awkward (brownfield project, loading an initial plain native screen - react native loads in the background). i create a `Release` bundle, so no extra network requests happening as the js in bundled.. but nothing ever completes. with detox 19 i get absolutely nothing, but with 18 it gets one step further. it doesnt solve my problem, but maybe you should give it a go, you never know what might happen.

**Comment by 2-b-error-3** [comment]
I got the same message when I was testing with Detox in iOS simulator and with every await device.reloadReactNative()  the simulator was displaying System Alert "Sign in with Apple ID".  If I did click manually on the alert after it pops up the message will not appear and the test passes. If don´t close the System Alert the same message will show and Detox tests fail with timeout error. Now I solved the issue with changes in app code, so that I won´t show the alerti in testing branch.

**Comment by pieter-mobile** [comment]
> I got the same message when I was testing with Detox in iOS simulator and with every await device.reloadReactNative() the simulator was displaying System Alert "Sign in with Apple ID". If I did click manually on the alert after it pops up the message will not appear and the test passes. If don´t close the System Alert the same message will show and Detox tests fail with timeout error. Now I solved the issue with changes in app code, so that I won´t show the alerti in testing branch.

Hi @2-b-error-3 , Could you share me the dependencies' version for both `expo` and `detox-cli`?

**Comment by dincho-kostadinov** [comment]
I got the same message when I try to run the tests on android environment . Any ideas or solution? 
Thanks in advance!

**Comment by viswathvs** [comment]
For anyone facing this issue — it could be caused by several factors, such as an infinite animation loop or long-running network requests. These can block the main thread and make the app unresponsive.

Try using device.disableSynchronization() before navigating to the screen where your app crashes, and then re-enable it with device.enableSynchronization() after leaving that page.
This allows Detox to continue running the test without waiting for those background tasks to finish.
