### ISSUE TITLE
Scrolling to edge on FlatList succeeds without scrolling

### ISSUE THREAD

**Issue by j320** [wix/Detox#3072]
### Describe the bug
When interacting with a FlatList, using the _scrollTo(edge)_ command will succeed but no action takes place.

This takes place both on Android and iOS, however on the demo project provided below, iOS hangs when running Detox so Android will have to be used in order to reproduce.
 
### Steps To Reproduce
1. Clone: https://github.com/j320/detox_scrolling 
2.  Build the app: _yarn android:build_
3.  Run the test _android:test:scrollToEdge_

### Expected behavior
Detox scrolls to the edge of the app and passes.

### Environment
 - Detox: 19.0.0
 - React Native: 0.62.2
 - OS: Android, iOS
 - Test-runner: jest-circus

**Comment by jonathanmos** [comment]
This is being caused by there being a flatlist inside a scrollview in your example, which is a known issue on android in react native (https://github.com/facebook/react-native/issues/19971). The simplest solution would be to remove the enclosing scrollview ("listBackground") and move the testID to the flatlist, and then it will scroll properly.
