### ISSUE TITLE
getAttributes "enabled" property

### ISSUE THREAD

**Issue by iMaupin** [wix/Detox#3203]
### Description

When crafting tests sometimes it is necessary to perform an action if an element is enabled or a different action if it is disabled.

Ideally, if a Button, Selector, ToubableOpacity, Pressable, or other react-native element is disabled, then 

`element(by.id("some_element_id)).getAttributes()`

should return an object where "enabled" = false.

Currently, it seems "enabled" _is always_ true.

What is the enabled key mapped to? Is there a way to make this work?

### Environment

 - Detox: 19
 - React Native: 0.66.3
 - Node: 14.17.6
 - Device: iOS/Android
 - Test-runner (select one): `jest-circus`

**Comment by asafkorem** [comment]
Hi @iMaupin, thanks for the report!

In iOS, the `enabled` attribute is `false` if one of the values of [enabled](https://developer.apple.com/documentation/uikit/uicontrol/1618217-enabled) or [userInteractionEnabled](https://developer.apple.com/documentation/uikit/uiview/1622577-userinteractionenabled?language=objc) is `false`, and `true` otherwise.
In Android, we expose the [isEnabled()](https://developer.android.com/reference/android/view/View#isEnabled()) value of the view element.

In both cases the value of `enabled` is not based on the [disabled](https://reactnative.dev/docs/switch#disabled) value of the RN component directly. 

Ideally, you are right, it can be very useful to know whether the `disabled` property has changed, but I also find this a bit weird that it isn't mapped to the native `enabled` in iOS or Android. I suggest to check with RN why it isn't the case..

From our side, we might want to consider exposing the `disabled` property of RN as well.

**Comment by AdamTyler** [comment]
@asafkorem is it possible to make the `enabled` attribute follow the RN `disabled` prop? That seems like it would make sense since most peoples buttons are most likely coming from RN. It sounds like maybe its a bug on the RN side that its not mapping to the OS level prop?
