### ISSUE TITLE
Detox launchingAPP

### ISSUE THREAD

**Issue by mckjs** [wix/Detox#3213]
### Description

 - Detox: 19.4.2
 - React Native: 0.67.2
 - React : 17.0.2
 - Node: 16.13.2
 - Device: Android
 - OS: Windows 10
 - Test-runner (select one): `jest-circus`

**Comment by d4vidi** [comment]
Hi and welcome to Detox 😃 
Based on your configuration, I see that you are trying to run your app in debug mode on a physical (aka attached) device, which can be a bit tricky.

A few suggestions:
1. After attaching the device, run the `adb devices` command; Locate the unique ID associated with your device and use it as the device name instead of `Galaxy S10`, in your `detoxrc.json` (as explained [here](https://wix.github.io/Detox/docs/introduction/android/#2-apply-detox-configuration)).
1. With the device still attached, run the adb reverse command in order to allow it to access the JS-bundling server (metro) running on your computer: `adb reverse tcp:8081 tcp:8081`
