### ISSUE TITLE
Backend API has valid response, but Detox is not getting the response (with Flipper installed)

### ISSUE THREAD

**Issue by finalight** [wix/Detox#3341]
### What happened?

I am running Detox on iOS, with backend (expressJS) running in localhost separately

I logged both the backend and frontend response body

When I run the detox test, the backend gave valid response body, but the frontend receives it `undefined`, even though the statusCode is 200

When i run without detox test, the network request is working fine.

I am not sure what am I missing to make the sure the network request body is not missing along the way...

### What was the expected behaviour?

When backend API gave valid response, the frontend should receive the same response

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Create a sample RN app, expressJS which returns some random response

Configure RN with detox and then have RN make network request to the expressJS app

Run the detox test

### In what environment did this happen?

Detox version: 19.4.3
React Native version: 0.67
Node version: 16
Device model: iphone 12
iOS version: 15
macOS version: monterey
Xcode version: 13.3.1
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

no logs

**Comment by finalight** [comment]
> Thanks for the report @finalight. However, this will be very hard to investigate without additional information.
> 
> Is it possible your backend uses the same port as Detox Server?

how can i fix the port on the detox? the port seems to be randomized

**Comment by asafkorem** [comment]
Please provide and check your logs using `--loglevel =trace` to get Detox port while running, also what's the backend port you're trying to communicate with?

**Comment by asafkorem** [comment]
Also, can you receive messages outside the app while the tests are running?

What module do you use to handle the network requests? Is it possible you're somehow mocking it in your code ([see mocking guide](https://wix.github.io/Detox/docs/guide/mocking/))?

**Comment by finalight** [comment]
> Please provide and check your logs using `--loglevel =trace` to get Detox port while running, also what's the backend port you're trying to communicate with?

i did a trace log but it might not be helpful, i will do it again later on
my backend port is on 3001, the detox seems to be using the port in the 50xxx range, as what I've checked using flipper network (yes i have flipper installed)

i am not sure what you meant by receve messages outside the app..

i am using axios to make network request, and I am not mocking the network request

**Comment by asafkorem** [comment]
@finalight this may help: https://github.com/wix/Detox/issues/2700#issuecomment-826471598

**Comment by finalight** [comment]
i not sure why would i want to do this since i already have a separate backend running

i am not doing a monorepo where it includes both mobile and backend source code together

**Comment by finalight** [comment]
i manage to find out the root cause; flipper is causing the issue.

is there anyway to run detox even with flipper installed?

**Comment by asafkorem** [comment]
@finalight what version of Flipper are you using?

**Comment by finalight** [comment]
> @finalight what version of Flipper are you using?

0.142

**Comment by asafkorem** [comment]
I'm not familiar with any issue of Detox & Flipper running together.
There's this old issue of Detox & Flipper: https://github.com/facebook/flipper/issues/1674, although it also seems to be resolved in v0.71: https://github.com/facebook/flipper/pull/1810

I'll try to reproduce this myself since I have no idea what could be causing the problem, probably next week. Running detox tests without Flipper works as expected, right?

**Comment by alekhinen** [comment]
hey everyone, just wanted to chime and say that my team has been experiencing the exact same issue. like @finalight said, this bug has to do with flipper.

we are running `react-native@0.67.4` and had `flipper@0.142.0`. bumping down to `0.99.0` fixes the issue for us. for reference, we no longer reference a specific flipper version in our podfile – see https://github.com/react-native-community/rn-diff-purge/blob/release/0.67.4/RnDiffApp/ios/Podfile#L24

**Comment by asafkorem** [comment]
@finalight are you still experiencing this issue?

**Comment by ovlesser** [comment]
This issue might be due to conflict between dependencies. Like in our project, we had similar issue after upgrading detox to 19.x.x, that the RN code was unable to receive valid response although it looks all good on the iOS native layer. After investigation, we found that is because the conflict between NewRelic and Detox.

**Comment by hongkheng** [comment]
Commenting on behalf of @finalight, tried with flipper version `0.128.0` and network requests are able to be made. The recent releases of flipper removed rsockets ref: https://github.com/facebook/flipper/issues/3554 due to Xcode 13.3. If this is the problem we might not be able to run detox tests in debug mode.

**Comment by josephk96** [comment]
Thanks @hongkheng , I haven't tried downgrading my flipper version yet, but after disabling the `#use_flipper` line in my `Podfile` my tests started to work again. I'm pretty sure your assumption that Flipper removing rsockets ref is the problem - when I run my Detox tests nothing can connect to my test server. However, when I kill the app and open it manually, I can connect normally. 

Not sure what's the solution here as I'm not familiar with rsockets. I know that this issue is not caused by Detox itself, but since Flipper is becoming more used (I personally used RN Debugger, but because Code Push stopped working properly without Hermes enabled on iOS I had to enable Hermes, which meant I had to use Flipper to debug my app properly), not being able to use Flipper is not really an option. If downgrading worked for @hongkheng , I'll just use a downgraded version of Flipper for now I guess.

**Comment by nzcodarnoc** [comment]
I'm experiencing this too, and just wrote a detailed report of my last two days debugging in another issue here: https://github.com/wix/Detox/issues/3424#issuecomment-1183968389

**Comment by nzcodarnoc** [comment]
Confirming the comment above https://github.com/wix/Detox/issues/3341#issuecomment-1115846128 (thank you @hongkheng !)

Fixing my Flipper version to `0.128.0` has resolved the issue for me.

**Comment by DaAitch** [comment]
We have the same problem, that when detox starts the app on the simulator none of the HTTP responses have a body and `JSON.parse('')` fails, so it's not even a network error.

When we write a detox test, that launches the app and wait a few seconds at first, we can manually close the app (really close by swiping away) and start the app again by clicking on it, everything starts to work and the test can run. This workaround is not possible with automatically terminate and relaunch the app. So this might be a hint, that the `launchApp(..)` makes the app start in a bad state with flipper, while starting the app by clicking on it not.

We currently fixed it by [commenting out](https://github.com/wix/Detox/issues/3341#issuecomment-1142054656) `# use_flipper!(..)`, but we should better try the [flipper downgrade](https://github.com/wix/Detox/issues/3341#issuecomment-1115846128).

If you need more information, please reach out.

**Comment by asafkorem** [comment]
This PR resolves the issue: https://github.com/wix/Detox/pull/3499
I'll release a patch version soon.

**Comment by asafkorem** [comment]
Please try upgrading Detox to version 19.8.1, then upgrade your Flipper version.

**Comment by josephk96** [comment]
> Please try to upgrade your Detox version to 19.8.1 (latest version ATM), then upgrade your Flipper version.

Hi @asafkorem , after upgrading Detox to 19.8.1 and Flipper to 0.155.0, everything is now working as expected. Thanks for the fix!

**Comment by asafkorem** [comment]
Great @josephk96! Thanks for the update.
