### ISSUE TITLE
typeText crashes detox with proguard on Android 

### ISSUE THREAD

**Issue by jahglow** [wix/Detox#3365]
### What happened?

```
DetoxRuntimeError: Test Failed: No static method arrayListOf([Ljava/lang/Object;)Ljava/util/ArrayList; in class Lu8/n; or its super classes (declaration of 'u8.n' appears in base.apk)
```

trying to execute `typeText` on an input, an app in production mode with detox installed as [compiling dependency](https://wix.github.io/Detox/docs/introduction/android/#setting-detox-up-as-a-compiling-dependency)

This [was said to be resolved](https://github.com/wix/Detox/issues/3010#issuecomment-940952256) in 18.2.2 

and adding proguard `-keep class kotlin.collections.** { *; }`  solves it as a workaround

### What was the expected behaviour?

not to fail

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.6.7
React Native version: 0.68.0
Node version: 16.9.1
Device model: OnePlus 3T
Android version: 9
Test-runner (select one): mocha

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by d4vidi** [comment]
@jahglow We have proguard running continuously on our Detox selt-test, which compiles Detox. It works because the `-keep class kotlin.collections.** { *; }` rule has been integarted to Detox's `proguard-rules-app.pro` file. Have you by any chance forgotten to [apply it in your proguard rules set](https://wix.github.io/Detox/docs/introduction/android/#7-proguard-minification-obfuscation)?

**Comment by mshafex** [comment]
same happens for me but i don't think its progaurd related since proguard isn't enabled in my debug build

environment 
Detox version: 19.6.5
React Native version: 0.67.2
Node version: 14.19.1
Device model: android emulator  
Android version: 11
Test-runner : mocha

app/build.gradle
[build.gradle.example.txt](https://github.com/wix/Detox/files/8669937/build.gradle.example.txt)

detox log 

```
15:32:02.514 detox[40245] WARN:  at e2e/login.spec.ts:6:17 
 APP RUN
    1) should login and logout


  0 passing (36s)
  1 failing

  1) Test Login flow
       should login and logout:
     Test Failed: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventInternal(InputManagerService.java:669)
	at com.android.server.input.InputManagerService.injectInputEvent(InputManagerService.java:643)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:430)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

  DetoxRuntimeError: Test Failed: Remote stack trace:
      at Context.<anonymous> (e2e/login.spec.ts:14:57)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)



15:32:08.229 detox[40244] ERROR: [cli.js] Command failed: mocha --config e2e/.mocharc.json --configuration android --grep :ios: --invert --use-custom-logger true e2e
```

**Comment by d4vidi** [comment]
(Dup of #3010)
