### ISSUE TITLE
[XCUITest] get missing white-box attributes for `getAttributes()` API.

### ISSUE THREAD

**Issue by asafkorem** [wix/Detox#3447]
Unfortunately, XCUIElement can give us limited list of attributes we currently return from `getAttributes()` API (on the current implementation of Detox-iOS).

The solution for that, will be to get the missing attributes (in which we can't get on the black-box side of the new iOS implementation, the XCUITest target) from the white-box side (using the Detox framework in which we inject to the application).
After that, the returned attributes will be a combination of "black-box" attributes (in which the XCUITest target has access to) and "white-box" attributes.

**Comment by LeoNatan** [comment]
Hello

Be careful because there is no uniqueness guarantees for identifiers. I found a way in the past to come between the accessibility query system. You can put a breakpoint in the `accessibilityIdentifier` getter to see how the system queries. You can swizzle there.

**Comment by asafkorem** [comment]
> Hello
> 
> Be careful because there is no uniqueness guarantees for identifiers. I found a way in the past to come between the accessibility query system. You can put a breakpoint in the `accessibilityIdentifier` getter to see how the system queries. You can swizzle there.

Thanks Leo,
That's a great point. I will definitely take that into account.
Chaining something unique to the identifier (or at least for those with multiple elements) may be worth a try, I can see how it might be problematic..
I also had in mind to pass more information regarding the element, `frame` and `exists` for example. This won't be perfect for that but this may be good enough in the vast majority of cases.

**Comment by asafkorem** [comment]
Another solution I was thinking of is - if there are multiple candidates for an element with the same identifier, the application can query the XCUITest target which element is the correct one, by **temporarily** changing their identifiers.

**Comment by LeoNatan** [comment]
The issue with passing more info is that information passes through XPC, which is very tight and would be a tall order to hack that (you don't have access to the accessibility daemon process).

It goes xcuiquery -> xpc -> accessbility daemon -> xpc -> app process -> iterate elements -> xpc -> accessbility daemon -> xctest. I couldn't find any effective way to attach additional data in that chain in a meaningful way, unless some of the known fields are modified. But I never really tested how feasible that is (for example, who else relies on these identifiers in the system—app or test or accessibility—which may fail due to swizzled identifier, for example.

My eventual plan was to have two distinct matcher/action systems and let the user pick from a custom—but limited—as the default, or the XCUI—for wider access in system processes and web—but with many known limitations.

Something like `element(by.id('app_login')).tap();` would use the default system, which is the custom matching and actions, but ``element.with_xcui(by.id('app_login')).tap();` would instead use the XCUI query system. XCUI is very limited and cannot be really relied on, especially for React Native. There isn't even `scroll()` action there. 🤣

**Comment by asafkorem** [comment]
Done
