### ISSUE TITLE
~1.5 seconds delay when hitting tap

### ISSUE THREAD

**Issue by larkox** [wix/Detox#3641]
### Description

I have a test similar to this:
```js
const t = Date.now()
await element(by.id(login)).tap()
const dt1 = Date.now() - t;
await waitFor(element(by.id(loggedIn))).toBeVisible().withTimeout(5000);
const dt2 = Date.now() - t;
```

The thing is that no matter how long it takes to have `loggedIn` visible, dt1 is always around 1.5 seconds. If the time to have `loggedIn` visible is small, `dt2-dt1` is really small (<100ms) but if the time is larger (e.g. 5 seconds) you see that dt1 is still 1.5 seconds, and `dt2-dt1` grows accordingly.

I was wondering where those 1.5 seconds come from, and if there is any way to bypass them.

The reasoning is to be able to use detox for performance testing automation.

### Your environment

Detox version: 19.12.6
React Native version: 0.70.3
Node version: 19.0.0
Device model: iOS simulator
OS: iOS 15.5
Test-runner (select one): jest

**Comment by d4vidi** [comment]
A `tap()` action (or virtually any Detox action) normally checks for visibility beforehand, and awaits the app to settle down, after (network, rendering, animations, timers...) - the latter being the fundamentals of the gray box testing principles Detox is based on. It is very likely that the 1.5 seconds are a direct response to things your app does after the tap.

Please try to utilize the [`debug-synchronization` CLI flag](https://wix.github.io/Detox/docs/troubleshooting/synchronization/) in order to inspect what's happening.
