### ISSUE TITLE
[RN 70] Test project compliance

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3735]

**Comment by agent-0028** [comment]
I am very excited to see this! We have a project with a decent set of e2e tests using Detox and we have had to temporarily shut them off in our pipeline because we needed to upgrade to RN 70 and enable the "new architecture". I am going to put this same message on all 4 of these issues for moral support and encouragement and so I am notified when there are updates!

**Comment by d4vidi** [comment]
Fixed by #3921
