### ISSUE TITLE
add a bluetooth permissions param to launchApp

### ISSUE THREAD

**Issue by NetanelH2** [wix/Detox#3880]
### Description

As I understand Detox is not able to test bluetooth feature based.
At least there is any way to add bluetooth permissions to the launchApp just to test features that count on the bluetooth state of the device.

The app my company develop is BLE based and we displaying a message to the user about bluetooth permissions and service turned on or off for example.

Thanks

### Your environment

Detox version: 20.1.1
React Native version: 0.70.5
Node version: 
Device model: 
OS: 
Test-runner (select one): Jest

**Comment by d4vidi** [comment]
@NetanelH2 I think the underlying details of what you're looking for reside in fact in [`AppleSimUtils` (ASU)](https://github.com/wix/AppleSimulatorUtils). [Contributing to that project](https://github.com/wix/AppleSimulatorUtils/blob/master/CONTRIBUTING.md) is fairly easy to do.

On top of that, in order to introduce the permission in Detox, you would have to also add it to its [types](https://github.com/wix/Detox/blob/a1c70efd4951589269af6269143cf8c9c9b9f2da/detox/index.d.ts#L1553) and [self-tests](https://github.com/wix/Detox/blob/1dca8733b2446e66a386b0d522809cb156d36855/detox/test/types/detox-module-tests.ts#L13) but the would be very subtle once you get past `ASU`.
