### ISSUE TITLE
Detox hang up with "• UI elements are busy:   - Reason: Animations running on screen."

### ISSUE THREAD

**Issue by eilinwis** [wix/Detox#3965]
### What happened?

Hello!
I'm trying to test some web elements on Android Emulator (AOSP).
I open a link in react-native app and then the browser opens and test hangs up

Here is my code:
```
const tapOnPrivatePolicy = async () => {
  await element(by.text('Privacy Policy').withAncestor(by.id(linksContainer))).tap()
  await expect(web.element(by.web.xpath('//h1[text()="Privacy Policy"]'))).toExist()
  await device.launchApp()
}
```

But after the tap browser opens and test hangs up with the message: 

14:29:53.009 detox[21683] i The app is busy with the following tasks:
• UI elements are busy:
  - Reason: Animations running on screen.
  
  I've tried to disable Synchronization and the result was the same with this message:

14:31:17.003 detox[21893] i The app seems to be idle

### What was the expected behaviour?

detox will execute code:

await expect(web.element(by.web.xpath('//h1[text()="Privacy Policy"]'))).toExist()

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.4.0
React Native version: 0.71.3
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 16.0
Device model: Android Emulator
Android version: 12 (AOSP)
Test-runner (select one): jest 

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by buraky84** [comment]
I have almost the same issue. I am on Animation page and test hangs with "reason":"UI rendering activity".

adding await device.disableSynchronization(); before the animation helped me to pass the animation step. However whenever i activate synchronization back await device.enableSynchronization(); it freezes again. 

If i never activate synchronization tests continue but on next steps other tests are failing due to synchronization needed.
This issue is only on Android. enableSynchronization() works fine on IOS and tests continue with %100 success.

For my experience device.enableSynchronization causes freeze on Android. 

According to DETOX release notes enableSynchronization issue should have already fixed by 19.11 release.
https://github.com/wix/Detox/releases/tag/19.11.0

Any ideas please?

DETOX: 20.6
RN: 71.6
Android AOSP 12.0 release

**Comment by jailsonpaca** [comment]
up

**Comment by mmjc29** [comment]
up
