### ISSUE TITLE
Updating Deprecated npm2yarn Commands for Compatibility with Yarn 2+

### ISSUE THREAD

**Issue by mustafahsz** [wix/Detox#4669]
### Describe your idea

You are using the `npm2yarn` package to convert `npm` commands to yarn commands. However, according to [this link](https://github.com/mixmaxhq/npm2yarn/issues/8#issuecomment-2558492569), this package is no longer being updated. As a result, the command it generates, `yarn global add detox-cli`, is incorrect. To make it usable, it should instead display the following command:

```bash
yarn dlx detox-cli
```

**Comment by noomorph** [comment]
Thanks for the suggestion, but `yarn dlx` won’t work for this purpose since it’s for one-off executions, not persistent global installs. That’s why I'd remove the `npm2yarn` conversion entirely and leave only the `npm` instructions in the docs. It keeps things simple and avoids confusing users.

See: https://github.com/wix/Detox/pull/4670

Thanks for checking this out. Sad to know that `npm2yarn` is no longer actively maintained, but we'll keep that in mind.
