### ISSUE TITLE
Fix doc generation to only run from master

### ISSUE THREAD

**Issue by rotemmiz** [wix/detox#542]
Docs generation seem to run from PRs as well currently, we need to make sure it only runs from master (or even better, only on releases) (https://github.com/wix/detox/blob/master/scripts/publish.sh)

While we're at it, generated docs have found their way into master, they need to be purged and git ignored.

**Comment by DanielMSchmidt** [comment]
Will take care of this on the weekend 👍

**Comment by DanielMSchmidt** [comment]
@rotemmiz Can you expand a bit what you mean exactly with "generated docs have found their way into master", I can't find them :(

**Comment by rotemmiz** [comment]
I might be wrong, is this generated ?https://github.com/wix/detox/tree/master/website/versioned_docs/version-6.X

If not,  can we make it generated ? I'm not sure we need to keep two (or more) copies of the same documentation just to version it.
How big of a hassle is it to create versioned docs (use git tags to determine releases, and the generate docs accordingly)

**Comment by DanielMSchmidt** [comment]
Ah, now I get you. This is the versioned doc for version 6.X. Every time we do a release bump we run `npm run version` in the `website/` directory. E.g. if we bump to 8.X and run the script it will create us a copy of our docs into `website/versioned_docs/version-7.X` so that users of older versions can use them later.
