### ISSUE TITLE
add ability to get the currently active configuration in a detox test

### ISSUE THREAD

**Issue by vonovak** [wix/Detox#634]
This is a feature request, please see [the SO question](https://stackoverflow.com/questions/49323694/how-to-get-the-currently-active-configuration-in-a-detox-test) for details.

**Comment by asafkorem** [comment]
It's been awhile since this issue was opened. However, if that's still relevant for you or for anyone else I encourage you to open this issue again.

Also, as it was answered in the SO post: https://stackoverflow.com/a/49426119/11686340, you can access the configuration argument in a non-official way. If you are reading this comment and this is relevant for you in any way please write us the use-case you're trying to solve and maybe there's a better way to do this (or we'll set you with one).

**Comment by phillip-kic** [comment]
We've recently had a use case for this.

In our tests we used test values that needed to change based on the app Build Type. Specifically [Branch](https://www.branch.io/) deep links that we are passing to `detox.device.openUrl` to test deep linking functionality. Debug builds need Branch Test links, and Release builds need Branch Live links.

The non-official solution linked above does not work anymore in version 20. What we've done instead is check an environment variable that's set in our build scripts and change the links used appropriately

**Comment by noomorph** [comment]
@phillip-kic it is quite trivial to get the current configuration in Detox 20:

https://wix.github.io/Detox/docs/api/internals/#config-runtimeconfig

https://github.com/wix/Detox/blob/ba39bbb92469425d7d70717c5f180da584e6756b/detox/internals.d.ts#L246
