### ISSUE TITLE
Run tests with different locales on each run

### ISSUE THREAD

**Issue by galfisher** [wix/Detox#683]

**Comment by rotemmiz** [comment]
Exactly,cwe should support this on both platforms though

**Comment by luisnaranjo733** [comment]
Is there an ETA on this? I need to be able to change the language of the app between detox tests for my use case.

It would be cool if this could be achieved by calling ```device.launchApp(language)``` in beforeEach(). It seems like this would be a pretty straightforward change to enable this on iOS at least (a great starting point).

Since I'm only running my tests on an iOS simulator, I think it's possible to hack this in for the meantime by somehow awaiting ```xcrun simctl launch booted <appid> -AppleLanguages "(en-GB)"``` in beforeEach like @LeoNatan alluded to. Please warn me if this is a bad idea or if I'm missing something :)

Just curious - is there already a public detox API for awaiting custom xcrum commands I can use in the meantime? I feel like I saw something like that somewhere while browsing through the GH issues.

**Comment by rotemmiz** [comment]
Yes please!!!

**Comment by rotemmiz** [comment]
BTW, seems like the Android solution is pretty straight forward as well, something like `adb shell setprop persist.sys.language en;setprop persist.sys.country US;stop;start`

**Comment by luisnaranjo733** [comment]
Cool! I went ahead and [opened the PR](https://github.com/wix/detox/pull/873).

**Comment by luisnaranjo733** [comment]
This issue can be closed :)
