### ISSUE TITLE
Provide API for taking screenshots on demand

### ISSUE THREAD

**Issue by luisnaranjo733** [wix/Detox#807]
The artifacts API in its current form enables screenshots to be easily taken before and after each test.
What if the test wants to take a screenshot at some arbitrary point in the middle of the test?

A few scenarios where this would be valuable:

- Using detox to take screenshots of various screens for QA purposes. If the tests could control when screenshots are taken, they could navigate, take a screenshot, and then repeat the cycle without having to restart the test to manually trigger an afterEach screenshot capture, thus saving time and effort.
- A test encounters an unexpected state in the middle of the test, and wants to capture the intermediary screen (that the afterEach screenshot may be too late to capture)
- A test just wants to capture a screenshot of some valid intermediary state for human sanity checking purposes that is not available at the end of the test.

Perhaps the API could look something like this:
```
// detox could append ".png" and put this in the same folder as beforeEach.png and afterEach.png
await device.takeScreenshot("exampleScreenShotName");
```

Would love to see what you guys think about this :)

**Comment by noomorph** [comment]
You see, my pull request in its very beginning had such an intent, thought later we came to conclusion that the scope of the change is too big and if you retrospectively take a look at the PR, it had about 100 commits and 100 changed files, succeeded by the other (not merged yet) pull request that adds unit test coverage to abstract artifact classes (plus 1500 lines approx.).

That was just too big to handle and grasp, so we postponed the imperative API till some time. I don't know what priority it has in Detox roadmap, but I also would love to see it readily available to anyone who needs it.

I hope I'll have a chance to work on it. Right now my priorities are to dramatically improve crashes, error handling and logs on Android and partially iOS, because as the life shows, Detox users are puzzled and disoriented at times by the verbose outputs

**Comment by luisnaranjo733** [comment]
I can totally see how that PR might have quickly become too big in scope with all of the infrastructural changes required to enable artifacts.

But it seems to me like the heavy lifting required to enable artifacts has already been done. You can already take screenshots before and after. Is it a lot more work to expose and document the existing screenshot artifacts API to the user so they can take screenshots in the middle?

At the end of the day, it's a just a call to adb or xcrun right?

**Comment by noomorph** [comment]
Yes, generally you are right, but there's still a question how to do it within the current architecture. I think I have a fairly good idea how, but it anyway needs a PoC (maybe I'm wrong about my way to do it) , a discussion with the maintainers (maybe they won't be happy about that way), a first implementation and maybe a consequent rework after a review and a couple discussions, so it is something that definitely is not going to happen sooner than in a month. Please mind that the latter is not an estimate, rather an advice to work around the current limitation if you need something already working for yesterday. I'm looking forward to this API too, so stay tuned - I'll be posting updates here as soon as the work starts on it.

**Comment by luisnaranjo733** [comment]
That makes total sense and is a super reasonable approach. I've subscribed to this issue so I'll definitely stay tuned. Thank you for the suggestion and thank you for following up on this!

**Comment by rodrigoelp** [comment]
Hi guys, I second this proposal. It would be so useful.

I've been using detox for a little while and I find it extremely good (trying to get our verification engineer to write the scenarios as specs so he can write down passing scenarios for bugs and other things). We capture so many images as part of our execution that is indescribable.

Here are my two cents about this conversation:

Ideally, what I would like to see as part of the interface of the object is (as described at the beginning):

- `await device.takeScreenshot("fileName")` but the file name is effectively just the file name as opposed to the entire path. On this definition, every time you call `takeScreenshot(fileName)` it generates a file `<artefacts_location>/<specification>/<test>/${fileName}.png`.

Optionally, don't provide customisation to it as you might need to validate the filePath... You could provide something like this:  every time you call `takeScreenshot()` it generates a file `<artefacts_location>/<specification>/<test>/<incrementalNumber_per_test>.png` which I think it would suit most people.

## Why am I making this request?

I know I can take a screenshot as:
`xcrun simctl io booted screenshot ${get the artefact folder}/${this.title}/${this.testTitle}/${number}.png`

But as it turns out, it kind of break as I try to run it with multiple workers because simctl will just execute the screenshot for the first booted instance. And you already have all the required information for the given instance (which is so nice).

I even though of forking the code and changing it myself (but failed after dedicating a few hours... couldn't follow all the abstraction and I might need a bit of guidance).

If you do this change, let me know and I will add type definitions as soon as possible and push it into `@types/detox`. Alternatively, I can do with some guidance about the changes we need to do and I will do the work and push it as a PR.
