### ISSUE TITLE
tvOS Support in Detox

### ISSUE THREAD

**Issue by Ljo2017** [wix/detox#836]
#### Description
Currently AppleTV is listed as one of the supported devices by applesimutils but when I tried running on Apple TV simulator, I get following error:

dyld: warning: could not load inserted library '/Users/Lewina/Library/Detox/ios/6835fdc9621ba06e099f505790cc7b06d2e6c1b5/Detox.framework/Detox' because no suitable image found.  Did find:
	/Users/Lewina/Library/Detox/ios/6835fdc9621ba06e099f505790cc7b06d2e6c1b5/Detox.framework/Detox: mach-o, but not built for tvOS simulator

Is there any plans to support Apple TV/Android TV in the future?

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 8.0.0
* React Native: 51
* Node: 8.9.4
* Device: Apple TV 4K 1080
* Xcode: 9.4.1
* macOS: 10.13.5

**Comment by LeoNatan** [comment]
Detox is not built currently with tvOS platform binary. We haven't looked into that yet. Since iOS and tvOS have very familiar APIs and SPIs, the support should not be hard to achieve. Further requirements would arise, such as supporting the Apple TV remote as Detox API to call in tests, as well as perhaps matchers and assertions for the focus system that exists in tvOS.

This is not on our focus right now, but if someone wants to help us achieve it, PRs are welcome.

**Comment by LeoNatan** [comment]
I don’t think Earl Grey supports tvOS, in which case this will not happen any time soon.
