### ISSUE TITLE
Detox scrolls warning area instead of real ListView

### ISSUE THREAD

**Issue by ihork** [wix/detox#85]
https://github.com/ihork/mobile-crash-course-imdb-clone/blob/51656517f757e7af68e1cf4167d8813a07864a42/e2e/filmList.spec.js#L22

**Comment by rotemmiz** [comment]
I think the issue revolves around the manipulation we do in this matcher: 
https://github.com/wix/detox/blob/master/detox/ios/Detox/GREYMatchers%2BDetox.m#L68

**Comment by silyevsk** [comment]
The element matcher works fine and finds the correct scroll view. But the scroll action starts at the bottom of the scroll view which is covered with the warning view.

To workaround this, it's possible to disable react native warnings in Javascript with `console. disableYellowBox = true`

In react native 0.44 the warning is disabled in test environment by default, and the test environment is on in detox (RN enables it if `XCTest` class exists which is loaded by EG).

While we don't have much to do with warnings specifically (because it's solved in recent RN and there's a workaround), the issue with EarlGrey should be still addressed, because it can happen for any covering view which reacts to pan gestures, and probably also for tap actions on overlapping views that react to taps (e.g. a button covering a view that reacts to taps).

**Comment by LeoNatan** [comment]
I think the workaround, together with the default mode in modern RN, is good enough for a solution right now. In the future, once we implement #154, the problem here will be moot, as the user will be able to specify where to start the scroll (pan) action, avoiding any clipping views, such as the warning area.

**Comment by silyevsk** [comment]
https://github.com/google/EarlGrey/issues/532
