### ISSUE TITLE
[question] improving detox workflow

### ISSUE THREAD

**Issue by vonovak** [wix/detox#851]
Hi, this not a bug but rather a question on how to improve my workflow. I already asked the question on stackoverflow but it didn't receive enough visibility: https://stackoverflow.com/questions/51100296/how-to-interact-with-detox-running-in-a-react-native-app

the gist of the question is this:

> I'd like to be able to set something like a breakpoint in a detox test and when I hit it, I'd like to be able to execute actions like await element(by.text('Done')).tap();.
>
> Or alternatively, I'd like to build the app with detox build, then manually get to a certain screen in the app and then again "connect to detox" and start executing the actions.

If anyone has any input on this, I'd be grateful, thanks.

**Comment by noomorph** [comment]
@vonovak, your question is a bit broad. Writing a comprehensive answer may take me a couple of hours net, and I'm already composing this reply for a good half an hour, so I wonder if you want to contribute to the debugging documentation? I'd appreciate if you find some time to answer own question on StackOverflow.

Let me show you an example with the Mocha runner. Examine the command produced by `detox test` CLI convenience method:

```
~/Projects/detox/examples/demo-react-native$ ./node_modules/.bin/detox test -c android.emu.debug

node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug     --grep :ios: --invert     --artifacts-location "artifacts/android.emu.debug.2018-07-24 07-52-12Z"
```

That raises the next question. How to debug mocha? Well, some googling helps, e.g., see https://stackoverflow.com/questions/41028932/run-node-inspector-with-mocha.

So all that you need is to add `--inspect-brk` flag to that command:

```
node_modules/.bin/mocha e2e --inspect-brk --opts e2e/mocha.opts --configuration android.emu.debug     --grep :ios: --invert     --artifacts-location "artifacts/android.emu.debug.2018-07-24 07-52-12Z"
```
Then you go to `chrome://inspect` to start debugging or follow the other docs here: https://nodejs.org/en/docs/guides/debugging-getting-started/.

Also, there are some other new kids on the block like [ndb](https://github.com/GoogleChromeLabs/ndb), although it's a matter of taste.

As you see, there's no black magic here, so I struggle to understand what makes detox different from other Node.js CLI tools in terms of debugging?

The workflow for Jest is going to be almost the same except that you'll have to export environment variables instead of command-line flags relying on this information: https://github.com/wix/detox/blob/master/detox/local-cli/detox-test.js#L133 . It is a bit tricker, but doable if you care to look into Bash, Zsh or whatever docs you might find relevant.

Best regards,
Yaroslav.

**Comment by noomorph** [comment]
Personally, I believe we could improve a thing or two regarding:

1) printing environment variables besides the actual command here: https://github.com/wix/detox/blob/master/detox/local-cli/detox-test.js#L145
2) having a short recipe section in documentation about the debugging

You're welcome to help.

**Comment by noomorph** [comment]
@vonovak , this is a follow-up of 1. Hope that will help you in the future. https://github.com/wix/detox/pull/852

It would be nice if you create PR to docs.
