### ISSUE TITLE
initialUrl config option

### ISSUE THREAD

**Issue by brentvatne** [wix/detox#90]
It would be useful to specify a url to open in the app so you can deep link into it for your tests. In particular this is useful to integrate with Exponent, so you can install the Exponent client and then if `initialUrl` is provided the app is opened with `fbsimctl open <initialUrl>` otherwise it just launches the app directly.

**Comment by LeoNatan** [comment]
This is already implemented internally. Not sure if already published in JS. @rotemmiz ?

Due to the way we inject Detox into iOS apps, we cannot use `fbsimctl open`. We have special API where you can launch your app using a URL, and it is rerouted to the app delegate as you expect from a launch with URL.

**Comment by rotemmiz** [comment]
@brentvatne do you mean something like this ? https://github.com/wix/detox/wiki/Mocking-User-Notifications-and-URLs#mocking-app-launch-from-a-url

**Comment by brentvatne** [comment]
nice :) that seems like it would do the trick
