### ISSUE TITLE
Add ability to pass parameters to app

### ISSUE THREAD

**Issue by Gongreg** [wix/detox#91]
We should be able to pass some kind of parameters into the app.

One use case for it would be being able to know that it is detox running the app and we could use different environments in the app.

**Comment by rotemmiz** [comment]
We are working on a solution for that.

The thing with `global.detox = true` is that it promotes bad coding practices. Your code should not be aware of what environment it runs under.  

The solution involves changes of how the react-native packager works, and will probably be implemented in different library. The end result should be something much stronger than just understanding that you run under detox. We want the users to be able to create `.detox.platform.js`files that will override `.platform.js` files, this way a user can override his configuration when using detox without the app having to know about it, which is a much better solution.

Since the scope of the ultimate solution is currently unknown, we will try implementing a temp and hacky solution to help users.

Stay tuned :)

**Comment by LeoNatan** [comment]
Also should be `.detox.js` to override platform-agnostic `.js` files.

**Comment by rotemmiz** [comment]
For a reference to others who read this thread, this is our solution for mocking environments.
https://github.com/wix/react-native-repackager
