### ISSUE TITLE
Add detox definitions

### ISSUE THREAD

**Issue by Gongreg** [wix/detox#99]
Having IDE support would really help writing tests. Since we have a lot of people liking typescript, something like DefinitelyTyped would help.

**Comment by rotemmiz** [comment]
Great suggestion! I love it. We'll put it in our plan. 
Alternatively, you can submit a PR, that would be very much appreciated.

**Comment by TareqElMasri** [comment]
I made the definitions, it's documented with examples, I'm waiting for the pull request to get approved, when it gets published, it will be used via `npm install @types/detox`
https://github.com/TareqElMasri/DefinitelyTyped/tree/master/types/detox

**Comment by tachtevrenidis** [comment]
did this PR ever make it in?

**Comment by DanielMSchmidt** [comment]
@tachtevrenidis There are still review comments, but it looks great otherwise 👍

**Comment by TareqElMasri** [comment]
Goodnews everyone, the PR made it successfully, now the maintainers need to create npm package for `@types/detox` using  [Types publisher tool](https://github.com/Microsoft/types-publisher)
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25005#issuecomment-381774947

**Comment by rotemmiz** [comment]
Hooray! Let's add this to docs and close this issue.

**Comment by TareqElMasri** [comment]
Fellas, it's up and running
https://www.npmjs.com/package/@types/detox

**Comment by DanielMSchmidt** [comment]
Awesome 👍  Let's close this issue then <3

**Comment by zibs** [comment]
Super awesome! Thanks for setting this up;

My only question is how to prevent the detox types from over-riding my jest types? Since detox overrides the jest object, it seems like when I'm trying to just write normal jest tests, TS still thinks the jest object is a detox one and so it complains for all the normal jest matchers/expects etc:

`[ts] Property 'toEqual' does not exist on type 'Expect<any>'.`

It's only small issue, so I don't feel like opening a new issue for it, but just curious if anyone has any ideas.
